# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AutoTuning and Calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        space_grotesk = QtGui.QFont(QtGui.QFontDatabase.applicationFontFamilies(QtGui.QFontDatabase.addApplicationFont(":/fonts/resources/fonts/SpaceGrotesk.ttf"))[0])

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4;\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    margin: -5px 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setFont(space_grotesk)
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout_2.addWidget(self.ImageSimulator)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AutotuningAndCalibration = QtWidgets.QWidget(self.Parameters)
        self.AutotuningAndCalibration.setMaximumSize(QtCore.QSize(16777215, 100))
        self.AutotuningAndCalibration.setObjectName("AutotuningAndCalibration")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.AutotuningAndCalibration)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ACLabel = QtWidgets.QLabel(self.AutotuningAndCalibration)
        self.ACLabel.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 26px;\n"
"padding: 0;\n"
"margin: 0;")
        self.ACLabel.setFont(space_grotesk)
        self.ACLabel.setObjectName("ACLabel")
        self.verticalLayout_7.addWidget(self.ACLabel)
        self.ACTextEdit = QtWidgets.QTextEdit(self.AutotuningAndCalibration)
        self.ACTextEdit.setEnabled(False)
        self.ACTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.ACTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.ACTextEdit.setStyleSheet("color: #94a3b8;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"background-color: #0f1b23;\n"
"border: None;")
        self.ACTextEdit.setFont(space_grotesk)
        self.ACTextEdit.setObjectName("ACTextEdit")
        self.verticalLayout_7.addWidget(self.ACTextEdit)
        self.verticalLayout_6.addWidget(self.AutotuningAndCalibration)
        self.BaseUploadImage = QtWidgets.QWidget(self.Parameters)
        self.BaseUploadImage.setMaximumSize(QtCore.QSize(16777215, 300))
        self.BaseUploadImage.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;")
        self.BaseUploadImage.setObjectName("BaseUploadImage")
        self.verticalLayoutBase = QtWidgets.QVBoxLayout(self.BaseUploadImage)
        self.verticalLayoutBase.setContentsMargins(12, 12, 12, 12)
        self.verticalLayoutBase.setSpacing(12)
        self.verticalLayoutBase.setObjectName("verticalLayoutBase")
        self.BaseUploadImageLabel = QtWidgets.QLabel(self.BaseUploadImage)
        self.BaseUploadImageLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BaseUploadImageLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.BaseUploadImageLabel.setFont(space_grotesk)
        self.BaseUploadImageLabel.setObjectName("BaseUploadImageLabel")
        self.verticalLayoutBase.addWidget(self.BaseUploadImageLabel)
        self.BaseUploadWidget = QtWidgets.QWidget(self.BaseUploadImage)
        self.BaseUploadWidget.setStyleSheet("border: 2px dashed rgb(75, 85, 99);\n"
"border-radius: 8px;")
        self.BaseUploadWidget.setObjectName("BaseUploadWidget")
        self.verticalLayout_3Base = QtWidgets.QVBoxLayout(self.BaseUploadWidget)
        self.verticalLayout_3Base.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_3Base.setSpacing(10)
        self.verticalLayout_3Base.setObjectName("verticalLayout_3Base")
        self.BaseUploadIcon = QtWidgets.QPushButton(self.BaseUploadWidget)
        self.BaseUploadIcon.setStyleSheet("border: None;")
        self.BaseUploadIcon.setText("")
        iconBase = QtGui.QIcon()
        iconBase.addPixmap(QtGui.QPixmap(":/icons/resources/icons/upload_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BaseUploadIcon.setIcon(iconBase)
        self.BaseUploadIcon.setIconSize(QtCore.QSize(50, 50))
        self.BaseUploadIcon.setObjectName("BaseUploadIcon")
        self.verticalLayout_3Base.addWidget(self.BaseUploadIcon)
        self.BaseUploadButton = QtWidgets.QPushButton(self.BaseUploadWidget)
        self.BaseUploadButton.setStyleSheet("border: None;\n"
"color: #e5e7eb;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"margin: 0;")
        self.BaseUploadButton.setFont(space_grotesk)
        self.BaseUploadButton.setObjectName("BaseUploadButton")
        self.verticalLayout_3Base.addWidget(self.BaseUploadButton)
        self.BaseConstraintsText = QtWidgets.QPushButton(self.BaseUploadWidget)
        self.BaseConstraintsText.setStyleSheet("border: None;\n"
"color: rgb(156, 163, 175);\n"
"font-size: 12px;\n"
"margin: 0;")
        self.BaseConstraintsText.setFont(space_grotesk)
        self.BaseConstraintsText.setObjectName("BaseConstraintsText")
        self.verticalLayout_3Base.addWidget(self.BaseConstraintsText)
        self.verticalLayoutBase.addWidget(self.BaseUploadWidget)
        self.verticalLayout_6.addWidget(self.BaseUploadImage)
        self.UploadImage = QtWidgets.QWidget(self.Parameters)
        self.UploadImage.setMaximumSize(QtCore.QSize(16777215, 300))
        self.UploadImage.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;")
        self.UploadImage.setObjectName("UploadImage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.UploadImage)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UploadImageLabel = QtWidgets.QLabel(self.UploadImage)
        self.UploadImageLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.UploadImageLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.UploadImageLabel.setFont(space_grotesk)
        self.UploadImageLabel.setObjectName("UploadImageLabel")
        self.verticalLayout.addWidget(self.UploadImageLabel)
        self.UploadWidget = QtWidgets.QWidget(self.UploadImage)
        self.UploadWidget.setStyleSheet("border: 2px dashed rgb(75, 85, 99);\n"
"border-radius: 8px;")
        self.UploadWidget.setObjectName("UploadWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.UploadWidget)
        self.verticalLayout_3.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UploadIcon = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadIcon.setStyleSheet("border: None;")
        self.UploadIcon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/upload_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadIcon.setIcon(icon1)
        self.UploadIcon.setIconSize(QtCore.QSize(50, 50))
        self.UploadIcon.setObjectName("UploadIcon")
        self.verticalLayout_3.addWidget(self.UploadIcon)
        self.UploadButton = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadButton.setStyleSheet("border: None;\n"
"color: #e5e7eb;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"margin: 0;")
        self.UploadButton.setFont(space_grotesk)
        self.UploadButton.setObjectName("UploadButton")
        self.verticalLayout_3.addWidget(self.UploadButton)
        self.ConstraintsText = QtWidgets.QPushButton(self.UploadWidget)
        self.ConstraintsText.setStyleSheet("border: None;\n"
"color: rgb(156, 163, 175);\n"
"font-size: 12px;\n"
"margin: 0;")
        self.ConstraintsText.setFont(space_grotesk)
        self.ConstraintsText.setObjectName("ConstraintsText")
        self.verticalLayout_3.addWidget(self.ConstraintsText)
        self.verticalLayout.addWidget(self.UploadWidget)
        self.verticalLayout_6.addWidget(self.UploadImage)
        self.BatchProcessing = QtWidgets.QWidget(self.Parameters)
        self.BatchProcessing.setMaximumSize(QtCore.QSize(16777215, 140))
        self.BatchProcessing.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;\n"
"background-color: #0f1b23;")
        self.BatchProcessing.setObjectName("BatchProcessing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.BatchProcessing)
        self.verticalLayout_4.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BatchProcessingLabel = QtWidgets.QLabel(self.BatchProcessing)
        self.BatchProcessingLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BatchProcessingLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.BatchProcessingLabel.setFont(space_grotesk)
        self.BatchProcessingLabel.setObjectName("BatchProcessingLabel")
        self.verticalLayout_4.addWidget(self.BatchProcessingLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.BatchProcessingExp = QtWidgets.QLabel(self.BatchProcessing)
        self.BatchProcessingExp.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BatchProcessingExp.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.BatchProcessingExp.setFont(space_grotesk)
        self.BatchProcessingExp.setObjectName("BatchProcessingExp")
        self.verticalLayout_4.addWidget(self.BatchProcessingExp)
        self.SelectImages = QtWidgets.QPushButton(self.BatchProcessing)
        self.SelectImages.setStyleSheet("border: None;\n"
"color: #1193d4;\n"
"background-color: #0f3244;\n"
"font-size: 14px;\n"
"margin: 12px 0px 0px;\n"
"padding: 8px 12px;\n"
"font-weight: 600;")
        self.SelectImages.setFont(space_grotesk)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/collections.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SelectImages.setIcon(icon2)
        self.SelectImages.setObjectName("SelectImages")
        self.verticalLayout_4.addWidget(self.SelectImages)
        self.verticalLayout_6.addWidget(self.BatchProcessing)
        self.ParameterLock = QtWidgets.QWidget(self.Parameters)
        self.ParameterLock.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ParameterLock.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;\n"
"background-color: #0f1b23;")
        self.ParameterLock.setObjectName("ParameterLock")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ParameterLock)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PLLabel = QtWidgets.QLabel(self.ParameterLock)
        self.PLLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.PLLabel.setFont(space_grotesk)
        self.PLLabel.setObjectName("PLLabel")
        self.verticalLayout_5.addWidget(self.PLLabel)
        self.PLExp = QtWidgets.QLabel(self.ParameterLock)
        self.PLExp.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.PLExp.setFont(space_grotesk)
        self.PLExp.setObjectName("PLExp")
        self.verticalLayout_5.addWidget(self.PLExp)
        
        # === START STYLE MODIFICATION ===
        # Replaced simple QCheckBoxes with styled toggle widgets
        self.DistortionPL = QtWidgets.QWidget(self.ParameterLock)
        self.DistortionPL.setStyleSheet("border: None;")
        self.DistortionPL.setObjectName("DistortionPL")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.DistortionPL)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DistortionPLLabel = QtWidgets.QLabel(self.DistortionPL)
        self.DistortionPLLabel.setStyleSheet("color: #d1d5db;\n"
"font-size: 14px;\n"
"")
        self.DistortionPLLabel.setFont(space_grotesk)
        self.DistortionPLLabel.setObjectName("DistortionPLLabel")
        self.horizontalLayout_3.addWidget(self.DistortionPLLabel)
        self.DistortionPLCB = QtWidgets.QCheckBox(self.DistortionPL)
        self.DistortionPLCB.setMinimumSize(QtCore.QSize(50, 26))
        self.DistortionPLCB.setMaximumSize(QtCore.QSize(50, 26))
        self.DistortionPLCB.setStyleSheet("QCheckBox {\n"
"    background-color: #4a5568;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    margin-left: 27px;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: #1193d4;\n"
"}")
        self.DistortionPLCB.setText("")
        self.DistortionPLCB.setObjectName("DistortionPLCB")
        self.horizontalLayout_3.addWidget(self.DistortionPLCB)
        self.verticalLayout_5.addWidget(self.DistortionPL)
        
        self.FLPL = QtWidgets.QWidget(self.ParameterLock)
        self.FLPL.setStyleSheet("border: None;")
        self.FLPL.setObjectName("FLPL")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.FLPL)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.FLPLLabel = QtWidgets.QLabel(self.FLPL)
        self.FLPLLabel.setStyleSheet("color: #d1d5db;\n"
"font-size: 14px;\n"
"")
        self.FLPLLabel.setFont(space_grotesk)
        self.FLPLLabel.setObjectName("FLPLLabel")
        self.horizontalLayout_7.addWidget(self.FLPLLabel)
        self.FLPLCB = QtWidgets.QCheckBox(self.FLPL)
        self.FLPLCB.setMinimumSize(QtCore.QSize(50, 26))
        self.FLPLCB.setMaximumSize(QtCore.QSize(50, 26))
        self.FLPLCB.setStyleSheet("QCheckBox {\n"
"    background-color: #4a5568;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    margin-left: 27px;\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: #1193d4;\n"
"}")
        self.FLPLCB.setText("")
        self.FLPLCB.setObjectName("FLPLCB")
        self.horizontalLayout_7.addWidget(self.FLPLCB)
        self.verticalLayout_5.addWidget(self.FLPL)
        # === END STYLE MODIFICATION ===

        self.verticalLayout_6.addWidget(self.ParameterLock)
        self.CameraOpticsSimulation = QtWidgets.QWidget(self.Parameters)
        self.CameraOpticsSimulation.setMaximumSize(QtCore.QSize(16777215, 140))
        self.CameraOpticsSimulation.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;\n"
"background-color: #0f1b23;")
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.CameraOpticsSimulation)
        self.verticalLayout_10.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.COSLabel = QtWidgets.QLabel(self.CameraOpticsSimulation)
        self.COSLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.COSLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.COSLabel.setFont(space_grotesk)
        self.COSLabel.setObjectName("COSLabel")
        self.verticalLayout_10.addWidget(self.COSLabel)
        self.COSExp = QtWidgets.QLabel(self.CameraOpticsSimulation)
        self.COSExp.setMaximumSize(QtCore.QSize(16777215, 30))
        self.COSExp.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.COSExp.setFont(space_grotesk)
        self.COSExp.setObjectName("COSExp")
        self.verticalLayout_10.addWidget(self.COSExp)
        self.verticalLayout_6.addWidget(self.CameraOpticsSimulation)
        
        # === REMOVED RunAutoTuning from left panel ===
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.Parameters)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        
        # === Add stretch factors from old UI ===
        self.verticalLayout_2.setStretch(0, 17)
        self.verticalLayout_2.setStretch(1, 275)
        self.verticalLayout_2.setStretch(2, 68)
        
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setStyleSheet("background-color: #0f1b23;") # Set background
        self.ImageWindow.setObjectName("ImageWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ImageWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        
        # === START STYLE MODIFICATION ===
        # Added TopRibbon from old UI
        self.TopRibbon = QtWidgets.QWidget(self.ImageWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulationLabel = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulationLabel.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulationLabel.setFont(space_grotesk)
        self.CameraOpticsSimulationLabel.setObjectName("CameraOpticsSimulationLabel")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulationLabel)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon3)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon4)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon5)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        # === END STYLE MODIFICATION ===
        
        
        # === START LAYOUT MODIFICATION ===
        # Replaced original simple ImagesWidget with styled layout from old UI
        self.ImagesWidget = QtWidgets.QWidget(self.ImageWindow)
        self.ImagesWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ImagesWidget.setObjectName("ImagesWidget")
        self.horizontalLayout_11_new = QtWidgets.QHBoxLayout(self.ImagesWidget)
        self.horizontalLayout_11_new.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11_new.setObjectName("horizontalLayout_11_new")
        self.LeftSpaceWidget_new = QtWidgets.QWidget(self.ImagesWidget)
        self.LeftSpaceWidget_new.setObjectName("LeftSpaceWidget_new")
        self.horizontalLayout_11_new.addWidget(self.LeftSpaceWidget_new)
        
        self.MiddleWidget_new = QtWidgets.QWidget(self.ImagesWidget)
        self.MiddleWidget_new.setStyleSheet("border-left: None;")
        self.MiddleWidget_new.setObjectName("MiddleWidget_new")
        
        self.verticalLayout_11_new = QtWidgets.QVBoxLayout(self.MiddleWidget_new)
        self.verticalLayout_11_new.setObjectName("verticalLayout_11_new")
        
        self.TopSpaceWidget_new = QtWidgets.QWidget(self.MiddleWidget_new)
        self.TopSpaceWidget_new.setStyleSheet("border: None;")
        self.TopSpaceWidget_new.setObjectName("TopSpaceWidget_new")
        self.verticalLayout_11_new.addWidget(self.TopSpaceWidget_new)

        # === START WIDGET CREATION (Moved from left panel) ===
        self.RunAutoTuning = QtWidgets.QWidget(self.MiddleWidget_new)
        self.RunAutoTuning.setMinimumSize(QtCore.QSize(0, 0))
        self.RunAutoTuning.setMaximumSize(QtCore.QSize(16777215, 175))
        self.RunAutoTuning.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;\n"
"background-color: #0f1b23;")
        self.RunAutoTuning.setObjectName("RunAutoTuning")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.RunAutoTuning)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        
        # Styled RATWidget
        self.RATWidget = QtWidgets.QWidget(self.RunAutoTuning)
        self.RATWidget.setStyleSheet("border: None;")
        self.RATWidget.setObjectName("RATWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.RATWidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.RATLabel = QtWidgets.QLabel(self.RATWidget)
        self.RATLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.RATLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.RATLabel.setFont(space_grotesk)
        self.RATLabel.setObjectName("RATLabel")
        self.horizontalLayout_10.addWidget(self.RATLabel)
        self.StartTuning = QtWidgets.QPushButton(self.RATWidget)
        self.StartTuning.setStyleSheet("QPushButton {\n"
"    background-color: #1193d4;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 8px 16px;\n" # Added padding
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #15a4e5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0f84bf;\n"
"    padding-top: 9px;\n"
"    padding-left: 17px;\n" # Adjusted padding
"}")
        self.StartTuning.setFont(space_grotesk)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/icons/bolt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartTuning.setIcon(icon6)
        self.StartTuning.setObjectName("StartTuning")
        self.horizontalLayout_10.addWidget(self.StartTuning)
        self.verticalLayout_11.addWidget(self.RATWidget)

        self.Progress = QtWidgets.QWidget(self.RunAutoTuning)
        self.Progress.setMinimumSize(QtCore.QSize(0, 75))
        self.Progress.setMaximumSize(QtCore.QSize(16777215, 200))
        self.Progress.setStyleSheet("border: None;\n"
"")
        self.Progress.setObjectName("Progress")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Progress)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ProgressLabels = QtWidgets.QWidget(self.Progress)
        self.ProgressLabels.setObjectName("ProgressLabels")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ProgressLabels)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.AutoTuningProgress = QtWidgets.QLabel(self.ProgressLabels)
        self.AutoTuningProgress.setStyleSheet("color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.AutoTuningProgress.setFont(space_grotesk)
        self.AutoTuningProgress.setObjectName("AutoTuningProgress")
        self.horizontalLayout_8.addWidget(self.AutoTuningProgress)
        self.ProgressPercent = QtWidgets.QLabel(self.ProgressLabels)
        self.ProgressPercent.setStyleSheet("color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.ProgressPercent.setFont(space_grotesk)
        self.ProgressPercent.setObjectName("ProgressPercent")
        self.horizontalLayout_8.addWidget(self.ProgressPercent, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_8.addWidget(self.ProgressLabels)
        self.ProgressBar = QtWidgets.QProgressBar(self.Progress)
        self.ProgressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ProgressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #4a5568;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    height: 16px;\n"
"    text-align: center;\n"
"    color: transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #1193d4;\n"
"    border-radius: 8px;\n"
"}")
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setTextVisible(False)
        self.ProgressBar.setObjectName("ProgressBar")
        self.verticalLayout_8.addWidget(self.ProgressBar)
        self.verticalLayout_11.addWidget(self.Progress)

        self.EstimatedParameters = QtWidgets.QWidget(self.MiddleWidget_new)
        self.EstimatedParameters.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.EstimatedParameters.setStyleSheet("border: 1px solid rgb(55, 65, 81);\n"
"border-radius: 8px;\n"
"background-color: #0f1b23;")
        self.EstimatedParameters.setObjectName("EstimatedParameters")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.EstimatedParameters)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.EstimatedParametersLabel = QtWidgets.QLabel(self.EstimatedParameters)
        self.EstimatedParametersLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.EstimatedParametersLabel.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 16px;\n"
"font-weight: 600;")
        self.EstimatedParametersLabel.setFont(space_grotesk)
        self.EstimatedParametersLabel.setObjectName("EstimatedParametersLabel")
        self.verticalLayout_9.addWidget(self.EstimatedParametersLabel)
        self.Distortion = QtWidgets.QWidget(self.EstimatedParameters)
        self.Distortion.setStyleSheet("border-left: None;\n"
"border-right: None;\n"
"border-top: None;\n"
"border-radius: 0px;")
        self.Distortion.setObjectName("Distortion")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Distortion)
        self.horizontalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.DistortionLabel = QtWidgets.QLabel(self.Distortion)
        self.DistortionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DistortionLabel.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.DistortionLabel.setFont(space_grotesk)
        self.DistortionLabel.setObjectName("DistortionLabel")
        self.horizontalLayout_13.addWidget(self.DistortionLabel)
        self.DistortionNumber = QtWidgets.QLabel(self.Distortion)
        self.DistortionNumber.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: 500;")
        self.DistortionNumber.setFont(space_grotesk)
        self.DistortionNumber.setObjectName("DistortionNumber")
        self.horizontalLayout_13.addWidget(self.DistortionNumber, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.Distortion)
        
        # === REMOVED "Noise" WIDGETS ===
        
        self.FL = QtWidgets.QWidget(self.EstimatedParameters)
        self.FL.setStyleSheet("border-left: None;\n"
"border-right: None;\n"
"border-top: None;\n"
"border-radius: 0px;")
        self.FL.setObjectName("FL")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.FL)
        self.horizontalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.FLLabel = QtWidgets.QLabel(self.FL)
        self.FLLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.FLLabel.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.FLLabel.setFont(space_grotesk)
        self.FLLabel.setObjectName("FLLabel")
        self.horizontalLayout_15.addWidget(self.FLLabel)
        self.FLNumber = QtWidgets.QLabel(self.FL)
        self.FLNumber.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: 500;")
        self.FLNumber.setFont(space_grotesk)
        self.FLNumber.setObjectName("FLNumber")
        self.horizontalLayout_15.addWidget(self.FLNumber, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.FL)
        self.SS = QtWidgets.QWidget(self.EstimatedParameters)
        self.SS.setStyleSheet("border-left: None;\n"
"border-right: None;\n"
"border-top: None;\n"
"border-radius: 0px;")
        self.SS.setObjectName("SS")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.SS)
        self.horizontalLayout_16.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.SSLabel = QtWidgets.QLabel(self.SS)
        self.SSLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SSLabel.setStyleSheet("border: None;\n"
"color: #9ca3af;\n"
"font-size: 14px;\n"
"")
        self.SSLabel.setFont(space_grotesk)
        self.SSLabel.setObjectName("SSLabel")
        self.horizontalLayout_16.addWidget(self.SSLabel)
        self.SSNumber = QtWidgets.QLabel(self.SS)
        self.SSNumber.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: 500;")
        self.SSNumber.setFont(space_grotesk)
        self.SSNumber.setObjectName("SSNumber")
        self.horizontalLayout_16.addWidget(self.SSNumber, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.SS)
        self.ApplyParameters = QtWidgets.QPushButton(self.EstimatedParameters)
        self.ApplyParameters.setStyleSheet("border: None;\n"
"color: #1193d4;\n"
"background-color: #0f3244;\n"
"font-size: 14px;\n"
"margin: 12px 0px 0px;\n"
"padding: 8px 12px;\n"
"font-weight: 600;")
        self.ApplyParameters.setFont(space_grotesk)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/icons/check_circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ApplyParameters.setIcon(icon7)
        self.ApplyParameters.setObjectName("ApplyParameters")
        self.verticalLayout_9.addWidget(self.ApplyParameters)
        # === END WIDGET CREATION ===

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        
        # Add widgets to the new middle layout
        self.verticalLayout_11_new.addWidget(self.RunAutoTuning)
        self.verticalLayout_11_new.addWidget(self.EstimatedParameters)
        self.verticalLayout_11_new.addItem(spacerItem1) # Add back the spacer

        # Add stretch factors from old UI
        self.verticalLayout_11_new.setStretch(0, 1)
        self.verticalLayout_11_new.setStretch(1, 4)
        self.verticalLayout_11_new.setStretch(2, 4)
        self.verticalLayout_11_new.setStretch(3, 4)
        
        self.horizontalLayout_11_new.addWidget(self.MiddleWidget_new)
        
        self.RightSpaceWidget_new = QtWidgets.QWidget(self.ImagesWidget)
        self.RightSpaceWidget_new.setStyleSheet("border-left: None;")
        self.RightSpaceWidget_new.setObjectName("RightSpaceWidget_new")
        self.horizontalLayout_11_new.addWidget(self.RightSpaceWidget_new)
        
        self.horizontalLayout_11_new.setStretch(0, 1)
        self.horizontalLayout_11_new.setStretch(1, 5)
        self.horizontalLayout_11_new.setStretch(2, 1)
        
        self.verticalLayout_14.addWidget(self.ImagesWidget)
        
        # Add stretch factors from old UI
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        # === END LAYOUT MODIFICATION ===

        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.ACLabel.setText(_translate("MainWindow", "Auto-Tuning & Calibration"))
        self.ACTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-size:14px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:400;\">Fine-tune your simulation parameters.</span></p></body></html>"))
        self.BaseUploadImageLabel.setText(_translate("MainWindow", "Upload Base Image (Clean/Undistorted)"))
        self.BaseUploadButton.setText(_translate("MainWindow", "Click to upload or drag and drop"))
        self.BaseConstraintsText.setText(_translate("MainWindow", "SVG, PNG, JPG or GIF (max. 800x400px)"))
        self.UploadImageLabel.setText(_translate("MainWindow", "Upload Target Image (Modified)"))
        self.UploadButton.setText(_translate("MainWindow", "Click to upload or drag and drop"))
        self.ConstraintsText.setText(_translate("MainWindow", "SVG, PNG, JPG or GIF (max. 800x400px)"))
        self.BatchProcessingLabel.setText(_translate("MainWindow", "Batch Processing"))
        self.BatchProcessingExp.setText(_translate("MainWindow", "Analyse multiple images at once."))
        self.SelectImages.setText(_translate("MainWindow", "Select Images"))
        self.PLLabel.setText(_translate("MainWindow", "Parameter Lock"))
        self.PLExp.setText(_translate("MainWindow", "Exclude parameters from auto-tuning."))
        self.DistortionPLLabel.setText(_translate("MainWindow", "Distortion"))
        self.FLPLLabel.setText(_translate("MainWindow", "Focal Length"))
        self.COSLabel.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.COSExp.setText(_translate("MainWindow", "Simulate optical effects on the image."))
        
        # === STYLED WIDGETS TEXT ===
        self.CameraOpticsSimulationLabel.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.RATLabel.setText(_translate("MainWindow", "Run Auto-Tuning"))
        self.StartTuning.setText(_translate("MainWindow", "Start Tuning"))
        self.AutoTuningProgress.setText(_translate("MainWindow", "Auto-Tuning Progress"))
        self.ProgressPercent.setText(_translate("MainWindow", "0%"))
        self.EstimatedParametersLabel.setText(_translate("MainWindow", "Estimated Parameters"))
        self.DistortionLabel.setText(_translate("MainWindow", "Distortion (k1)")) # Updated Label
        self.DistortionNumber.setText(_translate("MainWindow", "0.00"))
        self.FLLabel.setText(_translate("MainWindow", "Focal Length (Scale)")) # Updated Label
        self.FLNumber.setText(_translate("MainWindow", "1.00"))
        self.SSLabel.setText(_translate("MainWindow", "Distortion Center"))
        self.SSNumber.setText(_translate("MainWindow", "0 x 0"))
        self.ApplyParameters.setText(_translate("MainWindow", "Apply Parameters to Simulator"))

import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())