# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Comparison and Metrics Display.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from HistogramWidget import HistogramWidget
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        space_grotesk = QtGui.QFont(QtGui.QFontDatabase.applicationFontFamilies(QtGui.QFontDatabase.addApplicationFont(":/fonts/resources/fonts/SpaceGrotesk.ttf"))[0])

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4;\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    margin: -5px 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setMaximumSize(QtCore.QSize(450, 16777215))
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setFont(space_grotesk)
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.ImageSimulator)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ComparisonMetrics = QtWidgets.QWidget(self.Parameters)
        self.ComparisonMetrics.setObjectName("ComparisonMetrics")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ComparisonMetrics)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ComparisonMetricsLabel = QtWidgets.QLabel(self.ComparisonMetrics)
        self.ComparisonMetricsLabel.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 26px;\n"
"padding: 0;\n"
"margin: 0;")
        self.ComparisonMetricsLabel.setFont(space_grotesk)
        self.ComparisonMetricsLabel.setObjectName("ComparisonMetricsLabel")
        self.verticalLayout_7.addWidget(self.ComparisonMetricsLabel)
        self.ComparisonMetricsTextEdit = QtWidgets.QTextEdit(self.ComparisonMetrics)
        self.ComparisonMetricsTextEdit.setEnabled(False)
        self.ComparisonMetricsTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.ComparisonMetricsTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ComparisonMetricsTextEdit.setStyleSheet("color: #94a3b8;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"background-color: #0f1b23;\n"
"border: None;")
        self.ComparisonMetricsTextEdit.setFont(space_grotesk)
        self.ComparisonMetricsTextEdit.setObjectName("ComparisonMetricsTextEdit")
        self.verticalLayout_7.addWidget(self.ComparisonMetricsTextEdit, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.ComparisonMetrics)
        self.RealImage = QtWidgets.QWidget(self.Parameters)
        self.RealImage.setObjectName("RealImage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.RealImage)
        self.verticalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RealImageLabel = QtWidgets.QLabel(self.RealImage)
        self.RealImageLabel.setStyleSheet("color: #ffffff;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.RealImageLabel.setFont(space_grotesk)
        self.RealImageLabel.setObjectName("RealImageLabel")
        self.verticalLayout_3.addWidget(self.RealImageLabel, 0, QtCore.Qt.AlignBottom)
        self.UploadWidget = QtWidgets.QWidget(self.RealImage)
        self.UploadWidget.setMinimumSize(QtCore.QSize(0, 278))
        self.UploadWidget.setMaximumSize(QtCore.QSize(16777215, 278))
        self.UploadWidget.setStyleSheet("border: 1px dashed #e5e7eb;\n"
"border-radius: 8px;")
        self.UploadWidget.setObjectName("UploadWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.UploadWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.UploadIcon = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadIcon.setStyleSheet("border: None;")
        self.UploadIcon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/upload_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadIcon.setIcon(icon1)
        self.UploadIcon.setIconSize(QtCore.QSize(50, 50))
        self.UploadIcon.setObjectName("UploadIcon")
        self.verticalLayout_2.addWidget(self.UploadIcon)
        self.UploadButton = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadButton.setStyleSheet("border: None;\n"
"color: #e5e7eb;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"margin: 0;")
        self.UploadButton.setFont(space_grotesk)
        self.UploadButton.setObjectName("UploadButton")
        self.verticalLayout_2.addWidget(self.UploadButton)
        self.BrowseFiles = QtWidgets.QPushButton(self.UploadWidget)
        self.BrowseFiles.setStyleSheet("border: None;\n"
"color: #ffffff;\n"
"font-size: 14px;\n"
"margin: 16px 0px 0px;\n"
"padding: 8px 16px;\n"
"background-color: #1193d4;\n"
"border-radius: 4px")
        self.BrowseFiles.setFont(space_grotesk)
        self.BrowseFiles.setObjectName("BrowseFiles")
        self.verticalLayout_2.addWidget(self.BrowseFiles)
        self.ConstraintsText = QtWidgets.QPushButton(self.UploadWidget)
        self.ConstraintsText.setStyleSheet("border: None;\n"
"color: rgb(156, 163, 175);\n"
"font-size: 12px;\n"
"margin: 0;")
        self.ConstraintsText.setFont(space_grotesk)
        self.ConstraintsText.setObjectName("ConstraintsText")
        self.verticalLayout_2.addWidget(self.ConstraintsText)
        self.verticalLayout_3.addWidget(self.UploadWidget)
        self.verticalLayout_5.addWidget(self.RealImage)
        self.SimulatedImage = QtWidgets.QWidget(self.Parameters)
        self.SimulatedImage.setObjectName("SimulatedImage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SimulatedImage)
        self.verticalLayout_4.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SimulatedImageLabel = QtWidgets.QLabel(self.SimulatedImage)
        self.SimulatedImageLabel.setStyleSheet("color: #ffffff;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.SimulatedImageLabel.setFont(space_grotesk)
        self.SimulatedImageLabel.setObjectName("SimulatedImageLabel")
        self.verticalLayout_4.addWidget(self.SimulatedImageLabel, 0, QtCore.Qt.AlignBottom)
        self.SimulatedImageImage = QtWidgets.QLabel(self.SimulatedImage)
        self.SimulatedImageImage.setMinimumSize(QtCore.QSize(278, 0))
        self.SimulatedImageImage.setMaximumSize(QtCore.QSize(16777215, 278))
        self.SimulatedImageImage.setText("")
        self.SimulatedImageImage.setPixmap(QtGui.QPixmap(":/images/resources/images/simulated_default.png"))
        self.SimulatedImageImage.setScaledContents(True)
        self.SimulatedImageImage.setObjectName("SimulatedImageImage")
        self.verticalLayout_4.addWidget(self.SimulatedImageImage)
        self.verticalLayout_5.addWidget(self.SimulatedImage)
        spacerItem = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout.addWidget(self.Parameters)
        self.verticalLayout.setStretch(0, 17)
        self.verticalLayout.setStretch(1, 343)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ResultsWindow = QtWidgets.QWidget(self.centralwidget)
        self.ResultsWindow.setStyleSheet("background-color: #0f1b23;")
        self.ResultsWindow.setObjectName("ResultsWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ResultsWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TopRibbon = QtWidgets.QWidget(self.ResultsWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulation = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulation.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulation.setFont(space_grotesk)
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulation)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon2)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon3)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon4)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        self.ResultsWidget = QtWidgets.QWidget(self.ResultsWindow)
        self.ResultsWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ResultsWidget.setObjectName("ResultsWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ResultsWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.TopResults = QtWidgets.QWidget(self.ResultsWidget)
        self.TopResults.setStyleSheet("")
        self.TopResults.setObjectName("TopResults")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TopResults)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ComparisonResults = QtWidgets.QWidget(self.TopResults)
        self.ComparisonResults.setStyleSheet("border: None;")
        self.ComparisonResults.setObjectName("ComparisonResults")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ComparisonResults)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ComparisonResultsLabel = QtWidgets.QLabel(self.ComparisonResults)
        self.ComparisonResultsLabel.setStyleSheet("color: #ffffff;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.ComparisonResultsLabel.setFont(space_grotesk)
        self.ComparisonResultsLabel.setObjectName("ComparisonResultsLabel")
        self.verticalLayout_8.addWidget(self.ComparisonResultsLabel, 0, QtCore.Qt.AlignTop)
        self.SSIMPSNR = QtWidgets.QWidget(self.ComparisonResults)
        self.SSIMPSNR.setObjectName("SSIMPSNR")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SSIMPSNR)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SSIM = QtWidgets.QWidget(self.SSIMPSNR)
        self.SSIM.setStyleSheet("color: #e2e8f0;\n"
"background-color: #0f172a;\n"
"border: 1px solid #1e293b;\n"
"border-radius: 8px;")
        self.SSIM.setObjectName("SSIM")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.SSIM)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.SSIMLabel = QtWidgets.QLabel(self.SSIM)
        self.SSIMLabel.setStyleSheet("color: #94a3b8;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"border: None;\n"
"")
        self.SSIMLabel.setFont(space_grotesk)
        self.SSIMLabel.setObjectName("SSIMLabel")
        self.verticalLayout_9.addWidget(self.SSIMLabel)
        self.SSIMValue = QtWidgets.QLabel(self.SSIM)
        self.SSIMValue.setStyleSheet("color: #ffffff;\n"
"font-size: 30px;\n"
"font-weight: 700;\n"
"border: None;")
        self.SSIMValue.setFont(space_grotesk)
        self.SSIMValue.setObjectName("SSIMValue")
        self.verticalLayout_9.addWidget(self.SSIMValue)
        self.horizontalLayout_4.addWidget(self.SSIM, 0, QtCore.Qt.AlignTop)
        self.PSNR = QtWidgets.QWidget(self.SSIMPSNR)
        self.PSNR.setStyleSheet("color: #e2e8f0;\n"
"background-color: #0f172a;\n"
"border: 1px solid #1e293b;\n"
"border-radius: 8px;")
        self.PSNR.setObjectName("PSNR")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.PSNR)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.PSNRLabel = QtWidgets.QLabel(self.PSNR)
        self.PSNRLabel.setStyleSheet("color: #94a3b8;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"border: None;")
        self.PSNRLabel.setFont(space_grotesk)
        self.PSNRLabel.setObjectName("PSNRLabel")
        self.verticalLayout_10.addWidget(self.PSNRLabel)
        self.PSNRValue = QtWidgets.QLabel(self.PSNR)
        self.PSNRValue.setStyleSheet("color: #ffffff;\n"
"font-size: 30px;\n"
"font-weight: 700;\n"
"border: None;")
        self.PSNRValue.setFont(space_grotesk)
        self.PSNRValue.setObjectName("PSNRValue")
        self.verticalLayout_10.addWidget(self.PSNRValue)
        self.horizontalLayout_4.addWidget(self.PSNR)
        self.verticalLayout_8.addWidget(self.SSIMPSNR, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.ComparisonResults)
        self.DifferenceImageMap = QtWidgets.QWidget(self.TopResults)
        self.DifferenceImageMap.setStyleSheet("border: None;")
        self.DifferenceImageMap.setObjectName("DifferenceImageMap")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DifferenceImageMap)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MapLabel = QtWidgets.QLabel(self.DifferenceImageMap)
        self.MapLabel.setStyleSheet("color: #ffffff;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.MapLabel.setFont(space_grotesk)
        self.MapLabel.setObjectName("MapLabel")
        self.verticalLayout_6.addWidget(self.MapLabel, 0, QtCore.Qt.AlignTop)
        self.MapImage = QtWidgets.QLabel(self.DifferenceImageMap)
        self.MapImage.setMinimumSize(QtCore.QSize(278, 0))
        self.MapImage.setMaximumSize(QtCore.QSize(16777215, 278))
        self.MapImage.setText("")
        self.MapImage.setPixmap(QtGui.QPixmap(":/images/resources/images/map_default.png"))
        self.MapImage.setScaledContents(True)
        self.MapImage.setObjectName("MapImage")
        self.verticalLayout_6.addWidget(self.MapImage)
        self.horizontalLayout_3.addWidget(self.DifferenceImageMap)
        self.verticalLayout_11.addWidget(self.TopResults)
        self.Histograms = QtWidgets.QWidget(self.ResultsWidget)
        self.Histograms.setObjectName("Histograms")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Histograms)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ImageAnalysis = QtWidgets.QLabel(self.Histograms)
        self.ImageAnalysis.setStyleSheet("color: #ffffff;\n"
"font-size: 18px;\n"
"font-weight: 600;\n"
"border: None;")
        self.ImageAnalysis.setFont(space_grotesk)
        self.ImageAnalysis.setObjectName("ImageAnalysis")
        self.verticalLayout_12.addWidget(self.ImageAnalysis)
        sample_data1 = np.random.normal(loc=128, scale=50, size=10000)
        sample_data2 = np.random.normal(loc=128, scale=50, size=10000)
        hist_values1, _ = np.histogram(sample_data1, bins=256, range=(0, 255))
        hist_values2, _ = np.histogram(sample_data2, bins=256, range=(0, 255))
        self.RealHistogramWidget = QtWidgets.QWidget(self.Histograms)
        self.RealHistogramWidget.setStyleSheet("background-color: rgb(15, 23, 42);\n"
"border: 1px solid rgb(30, 41, 59);\n"
"border-radius: 8px;")
        self.RealHistogramWidget.setObjectName("RealHistogramWidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.RealHistogramWidget)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.RealHistogram = HistogramWidget(self.RealHistogramWidget)
        self.RealHistogram.setObjectName("RealHistogram")
        self.RealHistogram.setTitle("Real Image")
        self.RealHistogram.setTitleFont(space_grotesk)
        self.RealHistogram.setTitleStyleSheet("color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"border: None;")
        self.RealHistogram.setData(hist_values1)
        self.verticalLayout_13.addWidget(self.RealHistogram)
        self.verticalLayout_12.addWidget(self.RealHistogramWidget)
        self.SimulatedHistogramWidget = QtWidgets.QWidget(self.Histograms)
        self.SimulatedHistogramWidget.setStyleSheet("background-color: rgb(15, 23, 42);\n"
"border: 1px solid rgb(30, 41, 59);\n"
"border-radius: 8px;")
        self.SimulatedHistogramWidget.setObjectName("SimulatedHistogramWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.SimulatedHistogramWidget)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.SimulatedHistogram = HistogramWidget(self.SimulatedHistogramWidget)
        self.verticalLayout_15.addWidget(self.SimulatedHistogram)
        self.verticalLayout_12.addWidget(self.SimulatedHistogramWidget)
        self.SimulatedHistogram.setObjectName("SimulatedHistogram")
        self.SimulatedHistogram.setTitle("Simulated Image")
        self.SimulatedHistogram.setTitleFont(space_grotesk)
        self.SimulatedHistogram.setTitleStyleSheet("color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"border: None;")
        self.SimulatedHistogram.setData(hist_values2)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 10)
        self.verticalLayout_12.setStretch(2, 10)
        self.verticalLayout_11.addWidget(self.Histograms)
        self.verticalLayout_11.setStretch(0, 44)
        self.verticalLayout_11.setStretch(1, 83)
        self.verticalLayout_14.addWidget(self.ResultsWidget)
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        self.horizontalLayout.addWidget(self.ResultsWindow)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.ComparisonMetricsLabel.setText(_translate("MainWindow", "Comparison Metrics"))
        self.ComparisonMetricsTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-size:14px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:400;\">Compare the simulated image with a real-world reference image.</span></p></body></html>"))
        self.RealImageLabel.setText(_translate("MainWindow", "Real Image"))
        self.UploadButton.setText(_translate("MainWindow", "Click to upload or drag and drop"))
        self.BrowseFiles.setText(_translate("MainWindow", "Browse Files"))
        self.ConstraintsText.setText(_translate("MainWindow", "SVG, PNG, JPG or GIF (max. 800x400px)"))
        self.SimulatedImageLabel.setText(_translate("MainWindow", "Simulated Image"))
        self.CameraOpticsSimulation.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.ComparisonResultsLabel.setText(_translate("MainWindow", "Comparison Results"))
        self.SSIMLabel.setText(_translate("MainWindow", "SSIM"))
        self.SSIMValue.setText(_translate("MainWindow", "0.00"))
        self.PSNRLabel.setText(_translate("MainWindow", "PSNR"))
        self.PSNRValue.setText(_translate("MainWindow", "0.0 dB"))
        self.MapLabel.setText(_translate("MainWindow", "Difference Image Map"))
        self.ImageAnalysis.setText(_translate("MainWindow", "Image Analysis"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
