# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Designer Presets and Customization.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4; /* Blue knob */\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px; /* Knob width */\n"
"    height: 18px; /* Knob height */\n"
"    border-radius: 9px; /* Make it a perfect circle */\n"
"    margin: -5px 0px; /* Center the knob on the groove */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5; /* Lighter blue on hover */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.ImageSimulator)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.Parameters)
        self.label.setStyleSheet("color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: bold;\n"
"font-size: 26px;\n"
"padding: 0;\n"
"margin: 0;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.Parameters)
        self.textEdit.setEnabled(False)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.textEdit.setStyleSheet("color: #94a3b8;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"background-color: #0f1b23;\n"
"border: None;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.Parameters)
        self.label_2.setStyleSheet("color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"padding: 0;\n"
"margin: 0;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.widget = QtWidgets.QWidget(self.Parameters)
        self.widget.setStyleSheet("QRadioButton {\n"
"    padding: 12px 16px;\n"
"    border: 1px solid #374151;\n"
"    background-color: #1c2a35;\n"
"    color: #ffffff;\n"
"    font-family: SpaceGrotesk;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    border-color: #4a5b67;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #0f3345;\n"
"    border-color: #0f3345;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_14.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_14.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_14.addWidget(self.radioButton_3)
        self.verticalLayout_3.addWidget(self.widget)
        self.Zoom = QtWidgets.QWidget(self.Parameters)
        self.Zoom.setEnabled(True)
        self.Zoom.setObjectName("Zoom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Zoom)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ZoomLabel = QtWidgets.QLabel(self.Zoom)
        self.ZoomLabel.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.verticalLayout_4.addWidget(self.ZoomLabel)
        self.ZoomSliderPart = QtWidgets.QWidget(self.Zoom)
        self.ZoomSliderPart.setObjectName("ZoomSliderPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ZoomSliderPart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ZoomSlider = QtWidgets.QSlider(self.ZoomSliderPart)
        self.ZoomSlider.setEnabled(True)
        self.ZoomSlider.setMaximum(100)
        self.ZoomSlider.setSingleStep(1)
        self.ZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomSlider.setObjectName("ZoomSlider")
        self.horizontalLayout_3.addWidget(self.ZoomSlider)
        self.ZoomNumber = QtWidgets.QLabel(self.ZoomSliderPart)
        self.ZoomNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.ZoomNumber.setObjectName("ZoomNumber")
        self.horizontalLayout_3.addWidget(self.ZoomNumber)
        self.verticalLayout_4.addWidget(self.ZoomSliderPart)
        self.verticalLayout_3.addWidget(self.Zoom)
        self.FOV = QtWidgets.QWidget(self.Parameters)
        self.FOV.setEnabled(True)
        self.FOV.setObjectName("FOV")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FOV)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.FOVLabel = QtWidgets.QLabel(self.FOV)
        self.FOVLabel.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.FOVLabel.setObjectName("FOVLabel")
        self.verticalLayout_5.addWidget(self.FOVLabel)
        self.FOVSliderPart = QtWidgets.QWidget(self.FOV)
        self.FOVSliderPart.setObjectName("FOVSliderPart")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.FOVSliderPart)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FOVSlider = QtWidgets.QSlider(self.FOVSliderPart)
        self.FOVSlider.setEnabled(True)
        self.FOVSlider.setMaximum(100)
        self.FOVSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FOVSlider.setObjectName("FOVSlider")
        self.horizontalLayout_4.addWidget(self.FOVSlider)
        self.FOVNumber = QtWidgets.QLabel(self.FOVSliderPart)
        self.FOVNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.FOVNumber.setObjectName("FOVNumber")
        self.horizontalLayout_4.addWidget(self.FOVNumber)
        self.verticalLayout_5.addWidget(self.FOVSliderPart)
        self.verticalLayout_3.addWidget(self.FOV)
        self.Distortion = QtWidgets.QWidget(self.Parameters)
        self.Distortion.setEnabled(True)
        self.Distortion.setObjectName("Distortion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Distortion)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DistortionLabel = QtWidgets.QLabel(self.Distortion)
        self.DistortionLabel.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.DistortionLabel.setObjectName("DistortionLabel")
        self.verticalLayout_6.addWidget(self.DistortionLabel)
        self.DistortionSliderPart = QtWidgets.QWidget(self.Distortion)
        self.DistortionSliderPart.setObjectName("DistortionSliderPart")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.DistortionSliderPart)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DistortionSlider = QtWidgets.QSlider(self.DistortionSliderPart)
        self.DistortionSlider.setEnabled(True)
        self.DistortionSlider.setMaximum(100)
        self.DistortionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DistortionSlider.setObjectName("DistortionSlider")
        self.horizontalLayout_5.addWidget(self.DistortionSlider)
        self.DistortionNumber = QtWidgets.QLabel(self.DistortionSliderPart)
        self.DistortionNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.DistortionNumber.setObjectName("DistortionNumber")
        self.horizontalLayout_5.addWidget(self.DistortionNumber)
        self.verticalLayout_6.addWidget(self.DistortionSliderPart)
        self.verticalLayout_3.addWidget(self.Distortion)
        self.widget.raise_()
        self.Zoom.raise_()
        self.FOV.raise_()
        self.Distortion.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.label_2.raise_()
        self.verticalLayout.addWidget(self.Parameters)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 17)
        self.verticalLayout.setStretch(1, 215)
        self.verticalLayout.setStretch(2, 128)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setStyleSheet("background-color: #0f1b23;")
        self.ImageWindow.setObjectName("ImageWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ImageWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TopRibbon = QtWidgets.QWidget(self.ImageWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulation = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulation.setStyleSheet("color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulation)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon1)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon2)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon3)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        self.ImagesWidget = QtWidgets.QWidget(self.ImageWindow)
        self.ImagesWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ImagesWidget.setObjectName("ImagesWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ImagesWidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.OriginalWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.OriginalWidget.setStyleSheet("border: None;")
        self.OriginalWidget.setObjectName("OriginalWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OriginalWidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.OriginalImage = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.OriginalImage.setObjectName("OriginalImage")
        self.verticalLayout_15.addWidget(self.OriginalImage)
        self.OriginalDefault = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.OriginalDefault.setText("")
        self.OriginalDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/uploaded_default.png"))
        self.OriginalDefault.setScaledContents(True)
        self.OriginalDefault.setObjectName("OriginalDefault")
        self.verticalLayout_15.addWidget(self.OriginalDefault)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 17)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.OriginalWidget)
        self.SimulatedWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.SimulatedWidget.setStyleSheet("border: None;")
        self.SimulatedWidget.setObjectName("SimulatedWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.SimulatedWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SimulatedImage = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.SimulatedImage.setObjectName("SimulatedImage")
        self.verticalLayout_16.addWidget(self.SimulatedImage)
        self.SimulatedDefault = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.SimulatedDefault.setText("")
        self.SimulatedDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/simulated_default.png"))
        self.SimulatedDefault.setScaledContents(True)
        self.SimulatedDefault.setObjectName("SimulatedDefault")
        self.verticalLayout_16.addWidget(self.SimulatedDefault)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 17)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.SimulatedWidget)
        self.verticalLayout_14.addWidget(self.ImagesWidget)
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.label.setText(_translate("MainWindow", "Distortion Settings"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SpaceGrotesk\'; font-size:14px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:400;\">Select and adjust distortion types to simulate various lens effects.</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Distortion Type"))
        self.radioButton.setText(_translate("MainWindow", "Barrel"))
        self.radioButton_2.setText(_translate("MainWindow", "Pinpoint"))
        self.radioButton_3.setText(_translate("MainWindow", "None"))
        self.ZoomLabel.setText(_translate("MainWindow", "Intensity"))
        self.ZoomNumber.setText(_translate("MainWindow", "0"))
        self.FOVLabel.setText(_translate("MainWindow", "Center X"))
        self.FOVNumber.setText(_translate("MainWindow", "0"))
        self.DistortionLabel.setText(_translate("MainWindow", "Center Y"))
        self.DistortionNumber.setText(_translate("MainWindow", "0"))
        self.CameraOpticsSimulation.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.OriginalImage.setText(_translate("MainWindow", "Original Image"))
        self.SimulatedImage.setText(_translate("MainWindow", "Simulated Image"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
