# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Distortion Presets and Customization.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        space_grotesk = QtGui.QFont(QtGui.QFontDatabase.applicationFontFamilies(QtGui.QFontDatabase.addApplicationFont(":/fonts/resources/fonts/SpaceGrotesk.ttf"))[0])

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4; /* Blue knob */\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px; /* Knob width */\n"
"    height: 18px; /* Knob height */\n"
"    border-radius: 9px; /* Make it a perfect circle */\n"
"    margin: -5px 0px; /* Center the knob on the groove */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5; /* Lighter blue on hover */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setFont(space_grotesk)
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.ImageSimulator)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DistortionSettings = QtWidgets.QLabel(self.Parameters)
        self.DistortionSettings.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 26px;\n"
"padding: 0;\n"
"margin: 0;")
        self.DistortionSettings.setFont(space_grotesk)
        self.DistortionSettings.setObjectName("DistortionSettings")
        self.verticalLayout_3.addWidget(self.DistortionSettings)
        self.DistortionSettingsTextEdit = QtWidgets.QTextEdit(self.Parameters)
        self.DistortionSettingsTextEdit.setEnabled(False)
        self.DistortionSettingsTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.DistortionSettingsTextEdit.setStyleSheet("color: #94a3b8;\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"background-color: #0f1b23;\n"
"border: None;")
        self.DistortionSettingsTextEdit.setFont(space_grotesk)
        self.DistortionSettingsTextEdit.setFont(space_grotesk)
        self.DistortionSettingsTextEdit.setObjectName("DistortionSettingsTextEdit")
        self.verticalLayout_3.addWidget(self.DistortionSettingsTextEdit)
        self.DistortionType = QtWidgets.QLabel(self.Parameters)
        self.DistortionType.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"padding: 0;\n"
"margin: 0;")
        self.DistortionType.setFont(space_grotesk)
        self.DistortionType.setObjectName("DistortionType")
        self.verticalLayout_3.addWidget(self.DistortionType)
        self.DistortionTypeRadios = QtWidgets.QWidget(self.Parameters)
        self.DistortionTypeRadios.setStyleSheet("QRadioButton {\n"
"    padding: 12px 16px;\n"
"    border: 1px solid #374151;\n"
"    background-color: #1c2a35;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    border-color: #4a5b67;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #0f3345;\n"
"    border-color: #0f3345;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.DistortionTypeRadios.setFont(space_grotesk)
        self.DistortionTypeRadios.setObjectName("DistortionTypeRadios")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.DistortionTypeRadios)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Barrel = QtWidgets.QRadioButton(self.DistortionTypeRadios)
        self.Barrel.setObjectName("Barrel")
        self.horizontalLayout_14.addWidget(self.Barrel)
        self.Pinpoint = QtWidgets.QRadioButton(self.DistortionTypeRadios)
        self.Pinpoint.setObjectName("Pinpoint")
        self.horizontalLayout_14.addWidget(self.Pinpoint)
        self.Nonee = QtWidgets.QRadioButton(self.DistortionTypeRadios)
        self.Nonee.setObjectName("Nonee")
        self.horizontalLayout_14.addWidget(self.Nonee)
        self.verticalLayout_3.addWidget(self.DistortionTypeRadios)
        self.Intensity = QtWidgets.QWidget(self.Parameters)
        self.Intensity.setEnabled(True)
        self.Intensity.setObjectName("Intensity")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Intensity)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IntensityLabel = QtWidgets.QLabel(self.Intensity)
        self.IntensityLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.IntensityLabel.setFont(space_grotesk)
        self.IntensityLabel.setObjectName("IntensityLabel")
        self.verticalLayout_4.addWidget(self.IntensityLabel)
        self.IntensitySliderPart = QtWidgets.QWidget(self.Intensity)
        self.IntensitySliderPart.setObjectName("IntensitySliderPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.IntensitySliderPart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.IntensitySlider = QtWidgets.QSlider(self.IntensitySliderPart)
        self.IntensitySlider.setEnabled(True)
        self.IntensitySlider.setMaximum(100)
        self.IntensitySlider.setSingleStep(1)
        self.IntensitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.IntensitySlider.setObjectName("IntensitySlider")
        self.horizontalLayout_3.addWidget(self.IntensitySlider)
        self.IntensityNumber = QtWidgets.QLabel(self.IntensitySliderPart)
        self.IntensityNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.IntensityNumber.setObjectName("IntensityNumber")
        self.horizontalLayout_3.addWidget(self.IntensityNumber)
        self.verticalLayout_4.addWidget(self.IntensitySliderPart)
        self.verticalLayout_3.addWidget(self.Intensity)
        self.CenterX = QtWidgets.QWidget(self.Parameters)
        self.CenterX.setEnabled(True)
        self.CenterX.setObjectName("CenterX")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.CenterX)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CenterXLabel = QtWidgets.QLabel(self.CenterX)
        self.CenterXLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.CenterXLabel.setFont(space_grotesk)
        self.CenterXLabel.setObjectName("CenterXLabel")
        self.verticalLayout_5.addWidget(self.CenterXLabel)
        self.CenterXSliderPart = QtWidgets.QWidget(self.CenterX)
        self.CenterXSliderPart.setObjectName("CenterXSliderPart")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CenterXSliderPart)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CenterXSlider = QtWidgets.QSlider(self.CenterXSliderPart)
        self.CenterXSlider.setEnabled(True)
        self.CenterXSlider.setMaximum(100)
        self.CenterXSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CenterXSlider.setObjectName("CenterXSlider")
        self.horizontalLayout_4.addWidget(self.CenterXSlider)
        self.CenterXNumber = QtWidgets.QLabel(self.CenterXSliderPart)
        self.CenterXNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.CenterXNumber.setObjectName("CenterXNumber")
        self.horizontalLayout_4.addWidget(self.CenterXNumber)
        self.verticalLayout_5.addWidget(self.CenterXSliderPart)
        self.verticalLayout_3.addWidget(self.CenterX)
        self.CenterY = QtWidgets.QWidget(self.Parameters)
        self.CenterY.setEnabled(True)
        self.CenterY.setObjectName("CenterY")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.CenterY)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CenterYLabel = QtWidgets.QLabel(self.CenterY)
        self.CenterYLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.CenterYLabel.setFont(space_grotesk)
        self.CenterYLabel.setObjectName("CenterYLabel")
        self.verticalLayout_6.addWidget(self.CenterYLabel)
        self.CenterYSliderPart = QtWidgets.QWidget(self.CenterY)
        self.CenterYSliderPart.setObjectName("CenterYSliderPart")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CenterYSliderPart)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CenterYSlider = QtWidgets.QSlider(self.CenterYSliderPart)
        self.CenterYSlider.setEnabled(True)
        self.CenterYSlider.setMaximum(100)
        self.CenterYSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CenterYSlider.setObjectName("CenterYSlider")
        self.horizontalLayout_5.addWidget(self.CenterYSlider)
        self.CenterYNumber = QtWidgets.QLabel(self.CenterYSliderPart)
        self.CenterYNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.CenterYNumber.setObjectName("CenterYNumber")
        self.horizontalLayout_5.addWidget(self.CenterYNumber)
        self.verticalLayout_6.addWidget(self.CenterYSliderPart)
        self.verticalLayout_3.addWidget(self.CenterY)
        self.DistortionTypeRadios.raise_()
        self.Intensity.raise_()
        self.CenterX.raise_()
        self.CenterY.raise_()
        self.DistortionSettings.raise_()
        self.DistortionSettingsTextEdit.raise_()
        self.DistortionType.raise_()
        self.verticalLayout.addWidget(self.Parameters)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 17)
        self.verticalLayout.setStretch(1, 215)
        self.verticalLayout.setStretch(2, 128)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setStyleSheet("background-color: #0f1b23;")
        self.ImageWindow.setObjectName("ImageWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ImageWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TopRibbon = QtWidgets.QWidget(self.ImageWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulation = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulation.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulation.setFont(space_grotesk)
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulation)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon1)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon2)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon3)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        self.ImagesWidget = QtWidgets.QWidget(self.ImageWindow)
        self.ImagesWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ImagesWidget.setObjectName("ImagesWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ImagesWidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.OriginalWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.OriginalWidget.setStyleSheet("border: None;")
        self.OriginalWidget.setObjectName("OriginalWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OriginalWidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.OriginalImage = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.OriginalImage.setFont(space_grotesk)
        self.OriginalImage.setObjectName("OriginalImage")
        self.verticalLayout_15.addWidget(self.OriginalImage)
        self.OriginalDefault = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.OriginalDefault.setText("")
        self.OriginalDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/uploaded_default.png"))
        self.OriginalDefault.setScaledContents(True)
        self.OriginalDefault.setObjectName("OriginalDefault")
        self.verticalLayout_15.addWidget(self.OriginalDefault)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 17)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.OriginalWidget)
        self.SimulatedWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.SimulatedWidget.setStyleSheet("border: None;")
        self.SimulatedWidget.setObjectName("SimulatedWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.SimulatedWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SimulatedImage = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.SimulatedImage.setFont(space_grotesk)
        self.SimulatedImage.setObjectName("SimulatedImage")
        self.verticalLayout_16.addWidget(self.SimulatedImage)
        self.SimulatedDefault = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.SimulatedDefault.setText("")
        self.SimulatedDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/simulated_default.png"))
        self.SimulatedDefault.setScaledContents(True)
        self.SimulatedDefault.setObjectName("SimulatedDefault")
        self.verticalLayout_16.addWidget(self.SimulatedDefault)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 17)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.SimulatedWidget)
        self.verticalLayout_14.addWidget(self.ImagesWidget)
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.DistortionSettings.setText(_translate("MainWindow", "Distortion Settings"))
        self.DistortionSettingsTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-size:14px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:400;\">Select and adjust distortion types to simulate various lens effects.</span></p></body></html>"))
        self.DistortionType.setText(_translate("MainWindow", "Distortion Type"))
        self.Barrel.setText(_translate("MainWindow", "Barrel"))
        self.Pinpoint.setText(_translate("MainWindow", "Pinpoint"))
        self.Nonee.setText(_translate("MainWindow", "None"))
        self.IntensityLabel.setText(_translate("MainWindow", "Intensity"))
        self.IntensityNumber.setText(_translate("MainWindow", "0"))
        self.CenterXLabel.setText(_translate("MainWindow", "Center X"))
        self.CenterXNumber.setText(_translate("MainWindow", "0"))
        self.CenterYLabel.setText(_translate("MainWindow", "Center Y"))
        self.CenterYNumber.setText(_translate("MainWindow", "0"))
        self.CameraOpticsSimulation.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.OriginalImage.setText(_translate("MainWindow", "Original Image"))
        self.SimulatedImage.setText(_translate("MainWindow", "Simulated Image"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
