# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Sensor and Noise Parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from RangeSlider import RangeSlider


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        space_grotesk = QtGui.QFont(QtGui.QFontDatabase.applicationFontFamilies(QtGui.QFontDatabase.addApplicationFont(":/fonts/resources/fonts/SpaceGrotesk.ttf"))[0])

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4;\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    margin: -5px 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setFont(space_grotesk)
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout_2.addWidget(self.ImageSimulator)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SensorConfiguration = QtWidgets.QLabel(self.Parameters)
        self.SensorConfiguration.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 26px;\n"
"padding: 0;\n"
"margin: 0;")
        self.SensorConfiguration.setFont(space_grotesk)
        self.SensorConfiguration.setObjectName("SensorConfiguration")
        self.verticalLayout.addWidget(self.SensorConfiguration)
        self.NoiseLevel = QtWidgets.QWidget(self.Parameters)
        self.NoiseLevel.setEnabled(True)
        self.NoiseLevel.setObjectName("NoiseLevel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.NoiseLevel)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NoiseLevelLabel = QtWidgets.QLabel(self.NoiseLevel)
        self.NoiseLevelLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.NoiseLevelLabel.setFont(space_grotesk)
        self.NoiseLevelLabel.setObjectName("NoiseLevelLabel")
        self.verticalLayout_4.addWidget(self.NoiseLevelLabel)
        self.NoiseLevelSliderPart = QtWidgets.QWidget(self.NoiseLevel)
        self.NoiseLevelSliderPart.setObjectName("NoiseLevelSliderPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.NoiseLevelSliderPart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NoiseLevelSlider = QtWidgets.QSlider(self.NoiseLevelSliderPart)
        self.NoiseLevelSlider.setEnabled(True)
        self.NoiseLevelSlider.setMaximum(25)
        self.NoiseLevelSlider.setSingleStep(1)
        self.NoiseLevelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.NoiseLevelSlider.setObjectName("NoiseLevelSlider")
        self.horizontalLayout_3.addWidget(self.NoiseLevelSlider)
        self.NoiseLevelNumber = QtWidgets.QLabel(self.NoiseLevelSliderPart)
        self.NoiseLevelNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.NoiseLevelNumber.setObjectName("NoiseLevelNumber")
        self.horizontalLayout_3.addWidget(self.NoiseLevelNumber)
        self.verticalLayout_4.addWidget(self.NoiseLevelSliderPart)
        self.verticalLayout.addWidget(self.NoiseLevel)
        self.ExposureTime = QtWidgets.QWidget(self.Parameters)
        self.ExposureTime.setEnabled(True)
        self.ExposureTime.setObjectName("ExposureTime")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ExposureTime)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ExposureTimeLabel = QtWidgets.QLabel(self.ExposureTime)
        self.ExposureTimeLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ExposureTimeLabel.setFont(space_grotesk)
        self.ExposureTimeLabel.setObjectName("ExposureTimeLabel")
        self.verticalLayout_5.addWidget(self.ExposureTimeLabel)
        self.ExposureTimeSliderPart = QtWidgets.QWidget(self.ExposureTime)
        self.ExposureTimeSliderPart.setObjectName("ExposureTimeSliderPart")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ExposureTimeSliderPart)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ExposureTimeSlider = QtWidgets.QSlider(self.ExposureTimeSliderPart)
        self.ExposureTimeSlider.setEnabled(True)
        self.ExposureTimeSlider.setMaximum(500)
        self.ExposureTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ExposureTimeSlider.setObjectName("ExposureTimeSlider")
        self.horizontalLayout_4.addWidget(self.ExposureTimeSlider)
        self.ExposureTimeNumber = QtWidgets.QLabel(self.ExposureTimeSliderPart)
        self.ExposureTimeNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.ExposureTimeNumber.setObjectName("ExposureTimeNumber")
        self.horizontalLayout_4.addWidget(self.ExposureTimeNumber)
        self.verticalLayout_5.addWidget(self.ExposureTimeSliderPart)
        self.verticalLayout.addWidget(self.ExposureTime)
        self.DynamicRange = QtWidgets.QWidget(self.Parameters)
        self.DynamicRange.setEnabled(True)
        self.DynamicRange.setObjectName("DynamicRange")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.DynamicRange)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DynamicRangeLabel = QtWidgets.QLabel(self.DynamicRange)
        self.DynamicRangeLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.DynamicRangeLabel.setFont(space_grotesk)
        self.DynamicRangeLabel.setObjectName("DynamicRangeLabel")
        self.verticalLayout_6.addWidget(self.DynamicRangeLabel)
        self.DynamicRangePart = QtWidgets.QWidget(self.DynamicRange)
        self.DynamicRangePart.setObjectName("DynamicRangePart")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.DynamicRangePart)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # self.DynamicRangeSlider = QtWidgets.QSlider(self.DynamicRangePart)
        # self.DynamicRangeSlider.setEnabled(True)
        # self.DynamicRangeSlider.setMaximum(100)
        # self.DynamicRangeSlider.setOrientation(QtCore.Qt.Horizontal)
        # self.DynamicRangeSlider.setObjectName("DynamicRangeSlider")
        self.DynamicRangeSlider = RangeSlider(self.DynamicRangePart)
        self.DynamicRangeSlider.setRange(0, 255)
        self.DynamicRangeSlider.setLowerValue(0)
        self.DynamicRangeSlider.setUpperValue(255)
        self.horizontalLayout_5.addWidget(self.DynamicRangeSlider)
        self.DynamicRangeNumber = QtWidgets.QLabel(self.DynamicRangePart)
        self.DynamicRangeNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.DynamicRangeNumber.setObjectName("DynamicRangeNumber")
        self.horizontalLayout_5.addWidget(self.DynamicRangeNumber)
        self.verticalLayout_6.addWidget(self.DynamicRangePart)
        self.verticalLayout.addWidget(self.DynamicRange)
        self.SensorType = QtWidgets.QWidget(self.Parameters)
        self.SensorType.setEnabled(True)
        self.SensorType.setObjectName("SensorType")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.SensorType)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.SensorTypeLabel = QtWidgets.QLabel(self.SensorType)
        self.SensorTypeLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.SensorTypeLabel.setFont(space_grotesk)
        self.SensorTypeLabel.setObjectName("SensorTypeLabel")
        self.verticalLayout_10.addWidget(self.SensorTypeLabel)
        self.SensorTypeDropDown = QtWidgets.QComboBox(self.SensorType)
        self.SensorTypeDropDown.setStyleSheet("color: #e5e7eb;\n"
"font-size: 14px;\n"
"background-color: #1f2937;\n"
"padding: 8px 40px 8px 12px;\n"
"border-color: rgb(55 65 81);\n"
"border-radius: 4px")
        self.SensorTypeDropDown.setFont(space_grotesk)
        self.SensorTypeDropDown.setObjectName("SensorTypeDropDown")
        self.SensorTypeDropDown.addItem("")
        self.SensorTypeDropDown.addItem("")
        self.SensorTypeDropDown.addItem("")
        self.verticalLayout_10.addWidget(self.SensorTypeDropDown)
        self.verticalLayout.addWidget(self.SensorType)
        self.Resolution = QtWidgets.QWidget(self.Parameters)
        self.Resolution.setEnabled(True)
        self.Resolution.setObjectName("Resolution")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Resolution)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ResolutionLabel = QtWidgets.QLabel(self.Resolution)
        self.ResolutionLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ResolutionLabel.setFont(space_grotesk)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.verticalLayout_11.addWidget(self.ResolutionLabel)
        self.ResolutionDropDown = QtWidgets.QComboBox(self.Resolution)
        self.ResolutionDropDown.setStyleSheet("color: #e5e7eb;\n"
"font-size: 14px;\n"
"background-color: #1f2937;\n"
"padding: 8px 40px 8px 12px;\n"
"border-color: rgb(55 65 81);\n"
"border-radius: 4px")
        self.ResolutionDropDown.setFont(space_grotesk)
        self.ResolutionDropDown.setObjectName("ResolutionDropDown")
        self.ResolutionDropDown.addItem("")
        self.ResolutionDropDown.addItem("")
        self.ResolutionDropDown.addItem("")
        self.verticalLayout_11.addWidget(self.ResolutionDropDown)
        self.verticalLayout.addWidget(self.Resolution)
        self.ApplySettings = QtWidgets.QPushButton(self.Parameters)
        self.ApplySettings.setStyleSheet("QPushButton {\n"
"    background-color: #1193d4;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    padding: 8px 0px;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #15a4e5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0f84bf;\n"
"    padding-top: 9px;\n"
"    padding-left: 1px;\n"
"}")
        self.ApplySettings.setFont(space_grotesk)
        self.ApplySettings.setObjectName("ApplySettings")
        self.verticalLayout.addWidget(self.ApplySettings)
        self.NoiseLevel.raise_()
        self.ExposureTime.raise_()
        self.DynamicRange.raise_()
        self.SensorConfiguration.raise_()
        self.SensorType.raise_()
        self.Resolution.raise_()
        self.ApplySettings.raise_()
        self.verticalLayout_2.addWidget(self.Parameters)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.setStretch(0, 17)
        self.verticalLayout_2.setStretch(1, 215)
        self.verticalLayout_2.setStretch(2, 128)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setStyleSheet("background-color: #0f1b23;")
        self.ImageWindow.setObjectName("ImageWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ImageWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TopRibbon = QtWidgets.QWidget(self.ImageWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulation = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulation.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulation.setFont(space_grotesk)
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulation)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon1)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon2)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon3)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        self.ImagesWidget = QtWidgets.QWidget(self.ImageWindow)
        self.ImagesWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ImagesWidget.setObjectName("ImagesWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ImagesWidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.OriginalWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.OriginalWidget.setStyleSheet("border: None;")
        self.OriginalWidget.setObjectName("OriginalWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OriginalWidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.OriginalImage = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.OriginalImage.setFont(space_grotesk)
        self.OriginalImage.setObjectName("OriginalImage")
        self.verticalLayout_15.addWidget(self.OriginalImage)
        self.OriginalDefault = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.OriginalDefault.setText("")
        self.OriginalDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/uploaded_default.png"))
        self.OriginalDefault.setScaledContents(True)
        self.OriginalDefault.setObjectName("OriginalDefault")
        self.verticalLayout_15.addWidget(self.OriginalDefault)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 17)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.OriginalWidget)
        self.SimulatedWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.SimulatedWidget.setStyleSheet("border: None;")
        self.SimulatedWidget.setObjectName("SimulatedWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.SimulatedWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SimulatedImage = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.SimulatedImage.setFont(space_grotesk)
        self.SimulatedImage.setObjectName("SimulatedImage")
        self.verticalLayout_16.addWidget(self.SimulatedImage)
        self.SimulatedDefault = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.SimulatedDefault.setText("")
        self.SimulatedDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/simulated_default.png"))
        self.SimulatedDefault.setScaledContents(True)
        self.SimulatedDefault.setObjectName("SimulatedDefault")
        self.verticalLayout_16.addWidget(self.SimulatedDefault)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 17)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.SimulatedWidget)
        self.verticalLayout_14.addWidget(self.ImagesWidget)
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.DynamicRangeSlider.rangeChanged.connect(self.update_range_label)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def update_range_label(self, lower, upper):
        self.DynamicRangeNumber.setText(f"{lower} - {upper}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.SensorConfiguration.setText(_translate("MainWindow", "Sensor Configuration"))
        self.NoiseLevelLabel.setText(_translate("MainWindow", "Noise Level"))
        self.NoiseLevelNumber.setText(_translate("MainWindow", "0"))
        self.ExposureTimeLabel.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.ExposureTimeNumber.setText(_translate("MainWindow", "0"))
        self.DynamicRangeLabel.setText(_translate("MainWindow", "Dynamic Range"))
        self.DynamicRangeNumber.setText(_translate("MainWindow", "0 - 255"))
        self.SensorTypeLabel.setText(_translate("MainWindow", "Sensor Type"))
        self.SensorTypeDropDown.setItemText(0, _translate("MainWindow", "CMOS"))
        self.SensorTypeDropDown.setItemText(1, _translate("MainWindow", "CCD"))
        self.SensorTypeDropDown.setItemText(2, _translate("MainWindow", "sCMOS"))
        self.ResolutionLabel.setText(_translate("MainWindow", "Resolution"))
        self.ResolutionDropDown.setItemText(0, _translate("MainWindow", "1920 x 1080"))
        self.ResolutionDropDown.setItemText(1, _translate("MainWindow", "1280 x 720"))
        self.ResolutionDropDown.setItemText(2, _translate("MainWindow", "800 x 600"))
        self.ApplySettings.setText(_translate("MainWindow", "Apply Settings"))
        self.CameraOpticsSimulation.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.OriginalImage.setText(_translate("MainWindow", "Original Image"))
        self.SimulatedImage.setText(_translate("MainWindow", "Simulated Image"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
