# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulator Control Panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4; /* Blue knob */\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px; /* Knob width */\n"
"    height: 18px; /* Knob height */\n"
"    border-radius: 9px; /* Make it a perfect circle */\n"
"    margin: -5px 0px; /* Center the knob on the groove */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5; /* Lighter blue on hover */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fonts/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.label_2 = QtWidgets.QLabel(self.ImageSimulator)
        self.label_2.setEnabled(False)
        self.label_2.setStyleSheet("color: white;\n"
"font-family: SpaceGrotesk;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.ImageSimulator)
        self.widget_2 = QtWidgets.QWidget(self.Scrollers)
        self.widget_2.setStyleSheet("border: 1px dashed #cccccc;\n"
"border-radius: 8px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setStyleSheet("border: None;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/fonts/icons/upload_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setStyleSheet("border: None;\n"
"color: #e5e7eb;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"margin: 0;\n"
"font-family: SpaceGrotesk")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setStyleSheet("border: None;\n"
"color: rgb(156, 163, 175);\n"
"font-size: 12px;\n"
"margin: 0;\n"
"font-family: SpaceGrotesk")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.Scrollers)
        self.widget_3.setEnabled(True)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setStyleSheet("font-family: SpaceGrotesk;\n"
"color: #9ca3af;\n"
"font-size: 14px;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.widget_13 = QtWidgets.QWidget(self.widget)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_13)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.label_4 = QtWidgets.QLabel(self.widget_13)
        self.label_4.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.widget_13)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setEnabled(True)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.widget_14 = QtWidgets.QWidget(self.widget_5)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget_14)
        self.horizontalSlider_2.setEnabled(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.label_6 = QtWidgets.QLabel(self.widget_14)
        self.label_6.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setEnabled(True)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.widget_15 = QtWidgets.QWidget(self.widget_6)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget_15)
        self.horizontalSlider_3.setEnabled(True)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_3)
        self.label_8 = QtWidgets.QLabel(self.widget_15)
        self.label_8.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_6.addWidget(self.widget_15)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setEnabled(True)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.widget_11)
        self.label_17.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.widget_20 = QtWidgets.QWidget(self.widget_11)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.widget_20)
        self.horizontalSlider_8.setEnabled(True)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_8)
        self.label_18 = QtWidgets.QLabel(self.widget_20)
        self.label_18.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.verticalLayout_11.addWidget(self.widget_20)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setEnabled(True)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.widget_16 = QtWidgets.QWidget(self.widget_7)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.widget_16)
        self.horizontalSlider_4.setEnabled(True)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_4)
        self.label_10 = QtWidgets.QLabel(self.widget_16)
        self.label_10.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_7.addWidget(self.widget_16)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setEnabled(True)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.widget_17 = QtWidgets.QWidget(self.widget_8)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.widget_17)
        self.horizontalSlider_5.setEnabled(True)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_5)
        self.label_12 = QtWidgets.QLabel(self.widget_17)
        self.label_12.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout_8.addWidget(self.widget_17)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.widget_12 = QtWidgets.QWidget(self.widget_3)
        self.widget_12.setEnabled(True)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.widget_12)
        self.label_19.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.widget_21 = QtWidgets.QWidget(self.widget_12)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalSlider_9 = QtWidgets.QSlider(self.widget_21)
        self.horizontalSlider_9.setEnabled(True)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_9)
        self.label_20 = QtWidgets.QLabel(self.widget_21)
        self.label_20.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.verticalLayout_12.addWidget(self.widget_21)
        self.verticalLayout_3.addWidget(self.widget_12)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        self.widget_9.setEnabled(True)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.widget_9)
        self.label_13.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.widget_18 = QtWidgets.QWidget(self.widget_9)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.widget_18)
        self.horizontalSlider_6.setEnabled(True)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalLayout_8.addWidget(self.horizontalSlider_6)
        self.label_14 = QtWidgets.QLabel(self.widget_18)
        self.label_14.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.verticalLayout_9.addWidget(self.widget_18)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setEnabled(True)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.widget_10)
        self.label_15.setStyleSheet("font-family: SpaceGrotesk;\n"
"font-size: 14px;\n"
"color: #e5e7eb;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.comboBox = QtWidgets.QComboBox(self.widget_10)
        self.comboBox.setStyleSheet("font-family: SpaceGrotesk;\n"
"color: #e5e7eb;\n"
"font-size: 14px;\n"
"background-color: #1f2937;\n"
"padding: 8px 40px 8px 12px;\n"
"border-color: rgb(55 65 81);\n"
"border-radius: 4px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.Scrollers)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #0f3345;\n"
"    color: #1193d4;\n"
"    font-size: 14px;\n"
"    font-family: SpaceGrotesk;\n"
"    padding: 8px 0px;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #184e68;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0c2937;\n"
"    padding-top: 9px;\n"
"    padding-left: 1px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fonts/icons/settings_backup_restore.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_13.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #1193d4;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-family: SpaceGrotesk;\n"
"    padding: 8px 0px;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #15a4e5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0f84bf;\n"
"    padding-top: 9px;\n"
"    padding-left: 1px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/fonts/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_13.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.widget_4)
        self.verticalLayout.setStretch(0, 17)
        self.verticalLayout.setStretch(1, 80)
        self.verticalLayout.setStretch(2, 226)
        self.verticalLayout.setStretch(3, 37)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setObjectName("ImageWindow")
        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Image Simulator"))
        self.pushButton_2.setText(_translate("MainWindow", "Click to upload or drag and drop"))
        self.pushButton_3.setText(_translate("MainWindow", "SVG, PNG, JPG or GIF (max. 800x400px)"))
        self.label.setText(_translate("MainWindow", "PARAMETERS"))
        self.label_3.setText(_translate("MainWindow", "Zoom"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Field of View"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Distortion"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Brightness"))
        self.label_18.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Light Direction"))
        self.label_10.setText(_translate("MainWindow", "0°"))
        self.label_11.setText(_translate("MainWindow", "Shadows"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Noise"))
        self.label_20.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Exposure"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Resolution"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1920 x 1080"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1280 x 720"))
        self.comboBox.setItemText(2, _translate("MainWindow", "800 x 600"))
        self.pushButton_4.setText(_translate("MainWindow", "Reset"))
        self.pushButton_5.setText(_translate("MainWindow", "Apply"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
