# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulator Control Panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        space_grotesk = QtGui.QFont(QtGui.QFontDatabase.applicationFontFamilies(QtGui.QFontDatabase.addApplicationFont(":/fonts/resources/fonts/SpaceGrotesk.ttf"))[0])

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: #4a5568;\n"
"    border: 0px solid #4a5568;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #1193d4;\n"
"    border: 0px solid #1193d4;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    margin: -5px 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #15a4e5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scrollers = QtWidgets.QWidget(self.centralwidget)
        self.Scrollers.setEnabled(True)
        self.Scrollers.setStyleSheet("#Scrollers {\n"
"    background-color: #0f1b23;\n"
"}")
        self.Scrollers.setObjectName("Scrollers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Scrollers)
        self.verticalLayout.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImageSimulator = QtWidgets.QWidget(self.Scrollers)
        self.ImageSimulator.setStyleSheet("background-color: #0f1b23;")
        self.ImageSimulator.setObjectName("ImageSimulator")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSimulator)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.ImageSimulator)
        self.Icon.setStyleSheet("background-color: #1193d4;\n"
"color: white;\n"
"padding: 6px;\n"
"border: 2px solid #1193d4;\n"
"border-radius: 8px;")
        self.Icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/photo_camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon)
        self.Icon.setIconSize(QtCore.QSize(28, 28))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.ImageSimulatorText = QtWidgets.QLabel(self.ImageSimulator)
        self.ImageSimulatorText.setEnabled(False)
        self.ImageSimulatorText.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 28px;")
        self.ImageSimulatorText.setFont(space_grotesk)
        self.ImageSimulatorText.setScaledContents(True)
        self.ImageSimulatorText.setObjectName("ImageSimulatorText")
        self.horizontalLayout_2.addWidget(self.ImageSimulatorText)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.ImageSimulator)
        self.UploadWidget = QtWidgets.QWidget(self.Scrollers)
        self.UploadWidget.setStyleSheet("border: 1px dashed #e5e7eb;\n"
"border-radius: 8px;")
        self.UploadWidget.setObjectName("UploadWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.UploadWidget)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.UploadIcon = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadIcon.setStyleSheet("border: None;")
        self.UploadIcon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/upload_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadIcon.setIcon(icon1)
        self.UploadIcon.setIconSize(QtCore.QSize(50, 50))
        self.UploadIcon.setObjectName("UploadIcon")
        self.verticalLayout_2.addWidget(self.UploadIcon)
        self.UploadButton = QtWidgets.QPushButton(self.UploadWidget)
        self.UploadButton.setStyleSheet("border: None;\n"
"color: #e5e7eb;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"line-height: 20px;\n"
"margin: 0;\n")
        self.UploadButton.setFont(space_grotesk)
        self.UploadButton.setObjectName("UploadButton")
        self.verticalLayout_2.addWidget(self.UploadButton)
        self.ConstraintsText = QtWidgets.QPushButton(self.UploadWidget)
        self.ConstraintsText.setStyleSheet("border: None;\n"
"color: rgb(156, 163, 175);\n"
"font-size: 12px;\n"
"margin: 0;\n")
        self.ConstraintsText.setFont(space_grotesk)
        self.ConstraintsText.setObjectName("ConstraintsText")
        self.verticalLayout_2.addWidget(self.ConstraintsText)
        self.verticalLayout.addWidget(self.UploadWidget)
        self.Parameters = QtWidgets.QWidget(self.Scrollers)
        self.Parameters.setEnabled(True)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ParametersLabel = QtWidgets.QLabel(self.Parameters)
        self.ParametersLabel.setStyleSheet("color: #9ca3af;\n"
"font-size: 14px;")
        self.ParametersLabel.setFont(space_grotesk)
        self.ParametersLabel.setObjectName("ParametersLabel")
        self.verticalLayout_3.addWidget(self.ParametersLabel)
        self.Zoom = QtWidgets.QWidget(self.Parameters)
        self.Zoom.setEnabled(True)
        self.Zoom.setObjectName("Zoom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Zoom)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ZoomLabel = QtWidgets.QLabel(self.Zoom)
        self.ZoomLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ZoomLabel.setFont(space_grotesk)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.verticalLayout_4.addWidget(self.ZoomLabel)
        self.ZoomSliderPart = QtWidgets.QWidget(self.Zoom)
        self.ZoomSliderPart.setObjectName("ZoomSliderPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ZoomSliderPart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ZoomSlider = QtWidgets.QSlider(self.ZoomSliderPart)
        self.ZoomSlider.setEnabled(True)
        self.ZoomSlider.setMinimum(-100)
        self.ZoomSlider.setMaximum(100)
        self.ZoomSlider.setValue(0)
        self.ZoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomSlider.setObjectName("ZoomSlider")
        self.horizontalLayout_3.addWidget(self.ZoomSlider)
        self.ZoomNumber = QtWidgets.QLabel(self.ZoomSliderPart)
        self.ZoomNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.ZoomNumber.setObjectName("ZoomNumber")
        self.horizontalLayout_3.addWidget(self.ZoomNumber)
        self.verticalLayout_4.addWidget(self.ZoomSliderPart)
        self.verticalLayout_3.addWidget(self.Zoom)
        self.FOV = QtWidgets.QWidget(self.Parameters)
        self.FOV.setEnabled(True)
        self.FOV.setObjectName("FOV")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FOV)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.FOVLabel = QtWidgets.QLabel(self.FOV)
        self.FOVLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.FOVLabel.setFont(space_grotesk)
        self.FOVLabel.setObjectName("FOVLabel")
        self.verticalLayout_5.addWidget(self.FOVLabel)
        self.FOVSliderPart = QtWidgets.QWidget(self.FOV)
        self.FOVSliderPart.setObjectName("FOVSliderPart")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.FOVSliderPart)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FOVSlider = QtWidgets.QSlider(self.FOVSliderPart)
        self.FOVSlider.setEnabled(True)
        self.FOVSlider.setMinimum(10)
        self.FOVSlider.setMaximum(120)
        self.FOVSlider.setValue(60)
        self.FOVSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FOVSlider.setObjectName("FOVSlider")
        self.horizontalLayout_4.addWidget(self.FOVSlider)
        self.FOVNumber = QtWidgets.QLabel(self.FOVSliderPart)
        self.FOVNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.FOVNumber.setObjectName("FOVNumber")
        self.horizontalLayout_4.addWidget(self.FOVNumber)
        self.verticalLayout_5.addWidget(self.FOVSliderPart)
        self.verticalLayout_3.addWidget(self.FOV)
        self.Distortion = QtWidgets.QWidget(self.Parameters)
        self.Distortion.setEnabled(True)
        self.Distortion.setObjectName("Distortion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Distortion)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DistortionLabel = QtWidgets.QLabel(self.Distortion)
        self.DistortionLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.DistortionLabel.setFont(space_grotesk)
        self.DistortionLabel.setObjectName("DistortionLabel")
        self.verticalLayout_6.addWidget(self.DistortionLabel)
        self.DistortionSliderPart = QtWidgets.QWidget(self.Distortion)
        self.DistortionSliderPart.setObjectName("DistortionSliderPart")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.DistortionSliderPart)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DistortionSlider = QtWidgets.QSlider(self.DistortionSliderPart)
        self.DistortionSlider.setEnabled(True)
        self.DistortionSlider.setMaximum(500)
        self.DistortionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DistortionSlider.setObjectName("DistortionSlider")
        self.horizontalLayout_5.addWidget(self.DistortionSlider)
        self.DistortionNumber = QtWidgets.QLabel(self.DistortionSliderPart)
        self.DistortionNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.DistortionNumber.setObjectName("DistortionNumber")
        self.horizontalLayout_5.addWidget(self.DistortionNumber)
        self.verticalLayout_6.addWidget(self.DistortionSliderPart)
        self.verticalLayout_3.addWidget(self.Distortion)
        self.Brightness = QtWidgets.QWidget(self.Parameters)
        self.Brightness.setEnabled(True)
        self.Brightness.setObjectName("Brightness")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Brightness)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.BrightnessLabel = QtWidgets.QLabel(self.Brightness)
        self.BrightnessLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.BrightnessLabel.setFont(space_grotesk)
        self.BrightnessLabel.setObjectName("BrightnessLabel")
        self.verticalLayout_11.addWidget(self.BrightnessLabel)
        self.BrightnessSliderPart = QtWidgets.QWidget(self.Brightness)
        self.BrightnessSliderPart.setObjectName("BrightnessSliderPart")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.BrightnessSliderPart)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.BrightnessSlider = QtWidgets.QSlider(self.BrightnessSliderPart)
        self.BrightnessSlider.setEnabled(True)
        self.BrightnessSlider.setMinimum(-100)
        self.BrightnessSlider.setMaximum(100)
        self.BrightnessSlider.setValue(0)
        self.BrightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BrightnessSlider.setObjectName("BrightnessSlider")
        self.horizontalLayout_10.addWidget(self.BrightnessSlider)
        self.BrightnessNumber = QtWidgets.QLabel(self.BrightnessSliderPart)
        self.BrightnessNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.BrightnessNumber.setObjectName("BrightnessNumber")
        self.horizontalLayout_10.addWidget(self.BrightnessNumber)
        self.verticalLayout_11.addWidget(self.BrightnessSliderPart)
        self.verticalLayout_3.addWidget(self.Brightness)
        self.LD = QtWidgets.QWidget(self.Parameters)
        self.LD.setEnabled(True)
        self.LD.setObjectName("LD")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.LD)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LDLabel = QtWidgets.QLabel(self.LD)
        self.LDLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.LDLabel.setFont(space_grotesk)
        self.LDLabel.setObjectName("LDLabel")
        self.verticalLayout_7.addWidget(self.LDLabel)
        self.LDSliderPart = QtWidgets.QWidget(self.LD)
        self.LDSliderPart.setObjectName("LDSliderPart")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.LDSliderPart)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LDSlider = QtWidgets.QSlider(self.LDSliderPart)
        self.LDSlider.setEnabled(True)
        self.LDSlider.setMaximum(360)
        self.LDSlider.setValue(45)
        self.LDSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LDSlider.setObjectName("LDSlider")
        self.horizontalLayout_6.addWidget(self.LDSlider)
        self.LDNumber = QtWidgets.QLabel(self.LDSliderPart)
        self.LDNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.LDNumber.setObjectName("LDNumber")
        self.horizontalLayout_6.addWidget(self.LDNumber)
        self.verticalLayout_7.addWidget(self.LDSliderPart)
        self.verticalLayout_3.addWidget(self.LD)
        self.Shadows = QtWidgets.QWidget(self.Parameters)
        self.Shadows.setEnabled(True)
        self.Shadows.setObjectName("Shadows")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Shadows)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ShadowsLabel = QtWidgets.QLabel(self.Shadows)
        self.ShadowsLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ShadowsLabel.setFont(space_grotesk)
        self.ShadowsLabel.setObjectName("ShadowsLabel")
        self.verticalLayout_8.addWidget(self.ShadowsLabel)
        self.ShadowsSliderPart = QtWidgets.QWidget(self.Shadows)
        self.ShadowsSliderPart.setObjectName("ShadowsSliderPart")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ShadowsSliderPart)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ShadowsSlider = QtWidgets.QSlider(self.ShadowsSliderPart)
        self.ShadowsSlider.setEnabled(True)
        self.ShadowsSlider.setMaximum(100)
        self.ShadowsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ShadowsSlider.setObjectName("ShadowsSlider")
        self.horizontalLayout_7.addWidget(self.ShadowsSlider)
        self.ShadowsNumber = QtWidgets.QLabel(self.ShadowsSliderPart)
        self.ShadowsNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.ShadowsNumber.setObjectName("ShadowsNumber")
        self.horizontalLayout_7.addWidget(self.ShadowsNumber)
        self.verticalLayout_8.addWidget(self.ShadowsSliderPart)
        self.verticalLayout_3.addWidget(self.Shadows)
        self.Noise = QtWidgets.QWidget(self.Parameters)
        self.Noise.setEnabled(True)
        self.Noise.setObjectName("Noise")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Noise)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.NoiseLabel = QtWidgets.QLabel(self.Noise)
        self.NoiseLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.NoiseLabel.setFont(space_grotesk)
        self.NoiseLabel.setObjectName("NoiseLabel")
        self.verticalLayout_12.addWidget(self.NoiseLabel)
        self.NoiseSliderPart = QtWidgets.QWidget(self.Noise)
        self.NoiseSliderPart.setObjectName("NoiseSliderPart")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.NoiseSliderPart)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.NoiseSlider = QtWidgets.QSlider(self.NoiseSliderPart)
        self.NoiseSlider.setEnabled(True)
        self.NoiseSlider.setMaximum(25)
        self.NoiseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.NoiseSlider.setObjectName("NoiseSlider")
        self.horizontalLayout_11.addWidget(self.NoiseSlider)
        self.NoiseNumber = QtWidgets.QLabel(self.NoiseSliderPart)
        self.NoiseNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.NoiseNumber.setObjectName("NoiseNumber")
        self.horizontalLayout_11.addWidget(self.NoiseNumber)
        self.verticalLayout_12.addWidget(self.NoiseSliderPart)
        self.verticalLayout_3.addWidget(self.Noise)
        self.Exposure = QtWidgets.QWidget(self.Parameters)
        self.Exposure.setEnabled(True)
        self.Exposure.setObjectName("Exposure")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Exposure)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ExposureLabel = QtWidgets.QLabel(self.Exposure)
        self.ExposureLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ExposureLabel.setFont(space_grotesk)
        self.ExposureLabel.setObjectName("ExposureLabel")
        self.verticalLayout_9.addWidget(self.ExposureLabel)
        self.ExposureSliderPart = QtWidgets.QWidget(self.Exposure)
        self.ExposureSliderPart.setObjectName("ExposureSliderPart")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ExposureSliderPart)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ExposureSlider = QtWidgets.QSlider(self.ExposureSliderPart)
        self.ExposureSlider.setEnabled(True)
        self.ExposureSlider.setMaximum(100)
        self.ExposureSlider.setValue(50)
        self.ExposureSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ExposureSlider.setObjectName("ExposureSlider")
        self.horizontalLayout_8.addWidget(self.ExposureSlider)
        self.ExposureNumber = QtWidgets.QLabel(self.ExposureSliderPart)
        self.ExposureNumber.setStyleSheet("font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"font-size: 14px;\n"
"color: #9ca3af;")
        self.ExposureNumber.setObjectName("ExposureNumber")
        self.horizontalLayout_8.addWidget(self.ExposureNumber)
        self.verticalLayout_9.addWidget(self.ExposureSliderPart)
        self.verticalLayout_3.addWidget(self.Exposure)
        self.Resolution = QtWidgets.QWidget(self.Parameters)
        self.Resolution.setEnabled(True)
        self.Resolution.setObjectName("Resolution")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Resolution)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ResolutionLabel = QtWidgets.QLabel(self.Resolution)
        self.ResolutionLabel.setStyleSheet("font-size: 14px;\n"
"color: #e5e7eb;")
        self.ResolutionLabel.setFont(space_grotesk)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.verticalLayout_10.addWidget(self.ResolutionLabel)
        self.ResolutionDropDown = QtWidgets.QComboBox(self.Resolution)
        self.ResolutionDropDown.setStyleSheet("color: #e5e7eb;\n"
"font-size: 14px;\n"
"background-color: #1f2937;\n"
"padding: 8px 40px 8px 12px;\n"
"border-color: rgb(55 65 81);\n"
"border-radius: 4px")
        self.ResolutionDropDown.setFont(space_grotesk)
        self.ResolutionDropDown.setObjectName("ResolutionDropDown")
        self.ResolutionDropDown.addItem("")
        self.ResolutionDropDown.addItem("")
        self.ResolutionDropDown.addItem("")
        self.verticalLayout_10.addWidget(self.ResolutionDropDown)
        self.verticalLayout_3.addWidget(self.Resolution)
        self.verticalLayout.addWidget(self.Parameters)
        self.BottomButtons = QtWidgets.QWidget(self.Scrollers)
        self.BottomButtons.setObjectName("BottomButtons")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.BottomButtons)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Reset = QtWidgets.QPushButton(self.BottomButtons)
        self.Reset.setStyleSheet("QPushButton {\n"
"    background-color: #0f3345;\n"
"    color: #1193d4;\n"
"    font-size: 14px;\n"
"    padding: 8px 0px;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #184e68;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0c2937;\n"
"    padding-top: 9px;\n"
"    padding-left: 1px;\n"
"}")
        self.Reset.setFont(space_grotesk)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings_backup_restore.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Reset.setIcon(icon2)
        self.Reset.setObjectName("Reset")
        self.verticalLayout_13.addWidget(self.Reset)
        self.Apply = QtWidgets.QPushButton(self.BottomButtons)
        self.Apply.setStyleSheet("QPushButton {\n"
"    background-color: #1193d4;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    padding: 8px 0px;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #15a4e5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0f84bf;\n"
"    padding-top: 9px;\n"
"    padding-left: 1px;\n"
"}")
        self.Apply.setFont(space_grotesk)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Apply.setIcon(icon3)
        self.Apply.setObjectName("Apply")
        self.verticalLayout_13.addWidget(self.Apply)
        self.verticalLayout.addWidget(self.BottomButtons)
        self.verticalLayout.setStretch(0, 17)
        self.verticalLayout.setStretch(1, 80)
        self.verticalLayout.setStretch(2, 226)
        self.verticalLayout.setStretch(3, 37)
        self.horizontalLayout.addWidget(self.Scrollers)
        self.ImageWindow = QtWidgets.QWidget(self.centralwidget)
        self.ImageWindow.setStyleSheet("background-color: #0f1b23;")
        self.ImageWindow.setObjectName("ImageWindow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.ImageWindow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TopRibbon = QtWidgets.QWidget(self.ImageWindow)
        self.TopRibbon.setStyleSheet("background-color: #0f1b23;\n"
"border-left: 0.5px inset #243447;")
        self.TopRibbon.setObjectName("TopRibbon")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.TopRibbon)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CameraOpticsSimulation = QtWidgets.QLabel(self.TopRibbon)
        self.CameraOpticsSimulation.setStyleSheet("color: white;\n"
"font-weight: 700;\n"
"font-size: 20px;\n"
"border: None;")
        self.CameraOpticsSimulation.setFont(space_grotesk)
        self.CameraOpticsSimulation.setObjectName("CameraOpticsSimulation")
        self.horizontalLayout_9.addWidget(self.CameraOpticsSimulation)
        self.ToprightButtons = QtWidgets.QWidget(self.TopRibbon)
        self.ToprightButtons.setStyleSheet("border: None;")
        self.ToprightButtons.setObjectName("ToprightButtons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ToprightButtons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Help = QtWidgets.QPushButton(self.ToprightButtons)
        self.Help.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/icons/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon4)
        self.Help.setIconSize(QtCore.QSize(24, 24))
        self.Help.setObjectName("Help")
        self.horizontalLayout_12.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.ToprightButtons)
        self.Settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon5)
        self.Settings.setIconSize(QtCore.QSize(24, 24))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_12.addWidget(self.Settings)
        self.AccountBox = QtWidgets.QPushButton(self.ToprightButtons)
        self.AccountBox.setStyleSheet("")
        self.AccountBox.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/icons/account_box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBox.setIcon(icon6)
        self.AccountBox.setIconSize(QtCore.QSize(24, 24))
        self.AccountBox.setObjectName("AccountBox")
        self.horizontalLayout_12.addWidget(self.AccountBox)
        self.horizontalLayout_9.addWidget(self.ToprightButtons)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_14.addWidget(self.TopRibbon)
        self.ImagesWidget = QtWidgets.QWidget(self.ImageWindow)
        self.ImagesWidget.setStyleSheet("border-left: 0.5px inset #243447;\n"
"border-top: 0.5px inset #243447; ")
        self.ImagesWidget.setObjectName("ImagesWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.ImagesWidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.OriginalWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.OriginalWidget.setStyleSheet("border: None;")
        self.OriginalWidget.setObjectName("OriginalWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OriginalWidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.OriginalImage = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.OriginalImage.setFont(space_grotesk)
        self.OriginalImage.setObjectName("OriginalImage")
        self.verticalLayout_15.addWidget(self.OriginalImage)
        self.OriginalDefault = QtWidgets.QLabel(self.OriginalWidget)
        self.OriginalDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.OriginalDefault.setText("")
        self.OriginalDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/uploaded_default.png"))
        self.OriginalDefault.setScaledContents(True)
        self.OriginalDefault.setObjectName("OriginalDefault")
        self.verticalLayout_15.addWidget(self.OriginalDefault)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 17)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.OriginalWidget)
        self.SimulatedWidget = QtWidgets.QWidget(self.ImagesWidget)
        self.SimulatedWidget.setStyleSheet("border: None;")
        self.SimulatedWidget.setObjectName("SimulatedWidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.SimulatedWidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.SimulatedImage = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedImage.setStyleSheet("border: None;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;")
        self.SimulatedImage.setFont(space_grotesk)
        self.SimulatedImage.setObjectName("SimulatedImage")
        self.verticalLayout_16.addWidget(self.SimulatedImage)
        self.SimulatedDefault = QtWidgets.QLabel(self.SimulatedWidget)
        self.SimulatedDefault.setStyleSheet("border: None;\n"
"border-radius: 8px;")
        self.SimulatedDefault.setText("")
        self.SimulatedDefault.setPixmap(QtGui.QPixmap(":/images/resources/images/simulated_default.png"))
        self.SimulatedDefault.setScaledContents(True)
        self.SimulatedDefault.setObjectName("SimulatedDefault")
        self.verticalLayout_16.addWidget(self.SimulatedDefault)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem1)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 17)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_13.addWidget(self.SimulatedWidget)
        self.verticalLayout_14.addWidget(self.ImagesWidget)
        self.verticalLayout_14.setStretch(0, 8)
        self.verticalLayout_14.setStretch(1, 123)
        self.horizontalLayout.addWidget(self.ImageWindow)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ImageSimulatorText.setText(_translate("MainWindow", "Image Simulator"))
        self.UploadButton.setText(_translate("MainWindow", "Click to upload or drag and drop"))
        self.ConstraintsText.setText(_translate("MainWindow", "SVG, PNG, JPG or GIF (max. 800x400px)"))
        self.ParametersLabel.setText(_translate("MainWindow", "PARAMETERS"))
        self.ZoomLabel.setText(_translate("MainWindow", "Zoom"))
        self.ZoomNumber.setText(_translate("MainWindow", "0"))
        self.FOVLabel.setText(_translate("MainWindow", "Field of View"))
        self.FOVNumber.setText(_translate("MainWindow", "60°"))
        self.DistortionLabel.setText(_translate("MainWindow", "Distortion"))
        self.DistortionNumber.setText(_translate("MainWindow", "0"))
        self.BrightnessLabel.setText(_translate("MainWindow", "Brightness"))
        self.BrightnessNumber.setText(_translate("MainWindow", "0"))
        self.LDLabel.setText(_translate("MainWindow", "Light Direction"))
        self.LDNumber.setText(_translate("MainWindow", "0°"))
        self.ShadowsLabel.setText(_translate("MainWindow", "Shadows"))
        self.ShadowsNumber.setText(_translate("MainWindow", "0"))
        self.NoiseLabel.setText(_translate("MainWindow", "Noise"))
        self.NoiseNumber.setText(_translate("MainWindow", "0"))
        self.ExposureLabel.setText(_translate("MainWindow", "Exposure"))
        self.ExposureNumber.setText(_translate("MainWindow", "0"))
        self.ResolutionLabel.setText(_translate("MainWindow", "Resolution"))
        self.ResolutionDropDown.setItemText(0, _translate("MainWindow", "1920 x 1080"))
        self.ResolutionDropDown.setItemText(1, _translate("MainWindow", "1280 x 720"))
        self.ResolutionDropDown.setItemText(2, _translate("MainWindow", "800 x 600"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Apply.setText(_translate("MainWindow", "Apply"))
        self.CameraOpticsSimulation.setText(_translate("MainWindow", "Camera Optics Simulation"))
        self.OriginalImage.setText(_translate("MainWindow", "Original Image"))
        self.SimulatedImage.setText(_translate("MainWindow", "Simulated Image"))
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
